# -*- coding: utf-8 -*-
"""reviewed_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlWqFS8T8TAtVSCc8YqLA_fSp1iWjsyj
"""

# --- STEP 1: Load the file properly ---
import pandas as pd

# Read as tab-delimited (not CSV with commas!)
df = pd.read_csv("species_abundance.csv", sep="\t")

# Inspect
print(df.head())
print(df.shape)

# --- STEP 2: Pivot to species × samples matrix ---
# Rows = species, Columns = samples, Values = TPM
tpm_matrix = df.pivot_table(
    index="Taxon",
    columns="Sample_ID",
    values="TPM",
    aggfunc="mean"  # in case duplicates exist
)

# --- STEP 3: Save clean TPM matrix for R/limma ---
tpm_matrix.to_csv("TPM_matrix.csv")   # CSV format
tpm_matrix.to_csv("TPM_matrix.tsv", sep="\t")  # TSV (easier for R)

print(" TPM matrix saved! Shape:", tpm_matrix.shape)
