# -*- coding: utf-8 -*-
"""Fastqscreen_review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OQj87Vq1vvr7KPpVzI4OZpJuIaY3k6E
"""

# FastQ Screen contamination summary, tables, and plots — Colab-ready
# Fixes: safe row means with pandas, pivot_table observed=True, robust parsing and typing

BASE_DIR = "."

import re
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# -----------------------------
# Files and labels
# -----------------------------
FILES = {
    ("Ambulance",      "before1"): "ambulance_Fastqscreen_before1.csv",
    ("Ambulance",      "before2"): "ambulance_Fastqscreen_before2.csv",
    ("Hosp_env",       "before1"): "hosp_env_Fastqscreen_before1.csv",
    ("Hosp_env",       "before2"): "hosp_env_Fastqscreen_before2.csv",
    ("Hosp_sewage",    "before1"): "hosp_sewage_Fastqscreen_before1.csv",
    ("Hosp_sewage",    "before2"): "hosp_sewage_Fastqscreen_before2.csv",
    ("Public_transp",  "before1"): "public_transport_Fastqscreen_before1.csv",
    ("Public_transp",  "before2"): "public_transport_Fastqscreen_before2.csv",
}
ORDER_GROUPS   = ["Ambulance", "Hosp_env", "Hosp_sewage", "Public_transp"]
PALETTE_GROUPS = {"Ambulance": "#fdbf6f", "Hosp_env": "#aec7e8", "Hosp_sewage": "#ff7f0e", "Public_transp": "#1f77b4"}
PALETTE_CONTAM = {"Human": "#66c2a5", "Mouse": "#fc8d62", "Vectors": "#8da0cb", "Plasmodium": "#e78ac3"}

ALIASES = {
    "sample_id":        ["Sample_ID", "SampleID", "Sample", "sample_id"],
    "group":            ["Group", "group", "Source", "Env"],
    "reads_processed":  ["Reads processed", "Reads Processed", "Input reads", "Total reads", "reads_processed"],
    "unmapped_human":   ["unmapped_Human", "Unmapped_Human", "unmapped human", "Unmapped human"],
    "unmapped_mouse":   ["unmapped_Mouse", "Unmapped_Mouse", "unmapped mouse", "Unmapped mouse"],
    "unmapped_vectors": ["unmapped_Vectors", "Unmapped_Vectors", "unmapped vectors", "Unmapped vectors"],
    "unmapped_plas":    ["unmapped_Plasmodium", "Unmapped_Plasmodium", "unmapped plasmodium", "Unmapped plasmodium"],
}

# -----------------------------
# Helpers
# -----------------------------
def normalize_headers(cols):
    return [re.sub(r"\s+", " ", str(c).strip()) for c in cols]

def pick(df, options):
    lut = {c.lower(): c for c in df.columns}
    for opt in options:
        if opt.lower() in lut:
            return lut[opt.lower()]
    raise KeyError(f"None of {options} found in {list(df.columns)}")

def to_numeric_safe(x):
    s = pd.Series(x, dtype="string").str.replace(",", "", regex=False).str.replace("%", "", regex=False)
    return pd.to_numeric(s, errors="coerce")

def read_csv_robust(path: Path) -> pd.DataFrame:
    for sep in [",", "\t", ";"]:
        try:
            df = pd.read_csv(path, sep=sep, dtype=str, engine="python")
            if df.shape[1] >= 2:
                df.columns = normalize_headers(df.columns)
                return df
        except Exception:
            pass
    raise RuntimeError(f"Failed to parse {path}")

def style_axes(ax, spine_lw=2.2, tick_w=1.8):
    ax.grid(False)
    for s in ax.spines.values():
        s.set_linewidth(spine_lw)
        s.set_edgecolor("black")
    ax.tick_params(which="both", width=tick_w)
    ax.tick_params(which="major", length=6)
    ax.tick_params(which="minor", length=3)

def unmapped_to_percent(unmapped_series, reads_series):
    """Return percent [0..100] regardless of whether input is counts, fraction, or percent."""
    s  = to_numeric_safe(unmapped_series)
    rp = to_numeric_safe(reads_series)
    if s.notna().any():
        q95 = np.nanquantile(s, 0.95)
    else:
        q95 = np.nan
    if pd.notna(q95) and q95 <= 1.0:   # fraction
        return s * 100.0
    if pd.notna(q95) and q95 <= 100.0: # percent
        return s
    eps = 1e-12                         # counts
    return (s / (rp + eps)) * 100.0

# -----------------------------
# Load and compute contamination
# -----------------------------
base = Path(BASE_DIR)
rows, missing = [], []

for (env, rep), fname in FILES.items():
    p = base / fname
    if not p.exists():
        missing.append(str(p)); continue
    df_raw = read_csv_robust(p)

    c_sample = pick(df_raw, ALIASES["sample_id"])
    c_group  = pick(df_raw, ALIASES["group"])
    c_reads  = pick(df_raw, ALIASES["reads_processed"])
    c_human  = pick(df_raw, ALIASES["unmapped_human"])
    c_mouse  = pick(df_raw, ALIASES["unmapped_mouse"])
    c_vect   = pick(df_raw, ALIASES["unmapped_vectors"])
    c_plas   = pick(df_raw, ALIASES["unmapped_plas"])

    pu_human = unmapped_to_percent(df_raw[c_human], df_raw[c_reads])
    pu_mouse = unmapped_to_percent(df_raw[c_mouse], df_raw[c_reads])
    pu_vect  = unmapped_to_percent(df_raw[c_vect],  df_raw[c_reads])
    pu_plas  = unmapped_to_percent(df_raw[c_plas],  df_raw[c_reads])

    part = pd.DataFrame({
        "Sample_ID": df_raw[c_sample].astype(str).str.strip(),
        "Group":     df_raw[c_group].astype(str).str.strip(),
        "Replicate": rep,
        "Contam_Human":      100.0 - pu_human,
        "Contam_Mouse":      100.0 - pu_mouse,
        "Contam_Vectors":    100.0 - pu_vect,
        "Contam_Plasmodium": 100.0 - pu_plas,
        "Source_File": fname,
    })
    part["Group"] = np.where(part["Group"].isna() | (part["Group"] == ""), env, part["Group"])
    rows.append(part)

if missing:
    print("Warning, missing files:", missing)
if not rows:
    raise SystemExit("No input files could be read.")

df = pd.concat(rows, ignore_index=True)
df["Group"] = pd.Categorical(df["Group"], categories=ORDER_GROUPS, ordered=True)

# -----------------------------
# TABLE 1: Per-sample R1/R2 and averages
# -----------------------------
rep_map = {"before1": "R1", "before2": "R2"}
df["RepShort"] = df["Replicate"].map(rep_map).fillna(df["Replicate"])

wide = df.pivot_table(
    index=["Sample_ID","Group"],
    columns="RepShort",
    values=["Contam_Human","Contam_Mouse","Contam_Vectors","Contam_Plasmodium"],
    aggfunc="first",
    observed=True,  # silence future warning and keep category behavior explicit
)

# flatten MultiIndex -> "R1_Human", "R2_Mouse", ...
wide.columns = [f"{rep}_{lib}".replace("Contam_", "") for (lib, rep) in wide.columns.to_flat_index()]
wide = wide.reset_index()

# ensure numeric dtypes for R1/R2 columns
for col in [c for c in wide.columns if re.match(r"^(R1|R2)_(Human|Mouse|Vectors|Plasmodium)$", c)]:
    wide[col] = pd.to_numeric(wide[col], errors="coerce")

# safe row means with pandas, handles pd.NA
for lib in ["Human","Mouse","Vectors","Plasmodium"]:
    cols = [c for c in (f"R1_{lib}", f"R2_{lib}") if c in wide.columns]
    if cols:
        wide[f"Avg_{lib}"] = wide[cols].mean(axis=1, skipna=True)
    else:
        wide[f"Avg_{lib}"] = np.nan

# round for the presentation table (keeps underlying precision in memory if you need it)
wide_out = wide.copy()
to_round = [c for c in wide_out.columns if re.match(r"^(R1|R2|Avg)_(Human|Mouse|Vectors|Plasmodium)$", c)]
wide_out[to_round] = wide_out[to_round].round(2)
wide_out.to_csv("table1_contamination_per_sample_wide.tsv", sep="\t", index=False)

# -----------------------------
# TABLE 2: Group mean and SD of per-sample averages
# -----------------------------
avg_cols = [f"Avg_{k}" for k in ["Human","Mouse","Vectors","Plasmodium"]]
grp_stats = (wide.groupby("Group", observed=True)[avg_cols].agg(["mean","std"]))
grp_stats.columns = [f"{v} ± {stat}" for (v, stat) in grp_stats.columns.to_flat_index()]
grp_stats = grp_stats.reindex(ORDER_GROUPS).reset_index()
grp_stats["Group"] = grp_stats["Group"].replace({
    "Ambulance":"Ambulance", "Hosp_env":"hosp_env", "Hosp_sewage":"hosp_sewage", "Public_transp":"public_transport"
})
grp_stats_out = grp_stats.copy()
for c in grp_stats_out.columns[1:]:
    grp_stats_out[c] = grp_stats_out[c].round(2)
grp_stats_out.to_csv("table2_group_mean_sd.tsv", sep="\t", index=False)

# -----------------------------
# TABLE 3: One-way ANOVA per contaminant across groups
# -----------------------------
anova_rows = []
for lib in ["Human","Mouse","Vectors","Plasmodium"]:
    groups = []
    for g in ORDER_GROUPS:
        vals = wide.loc[wide["Group"]==g, f"Avg_{lib}"].dropna().values
        if len(vals) > 0:
            groups.append(vals)
    if len(groups) >= 2:
        F, p = stats.f_oneway(*groups)
        anova_rows.append({
            "Contaminant": lib,
            "F-statistic": round(float(F), 4),
            "p-value": "0" if p < 1e-4 else f"{p:.4f}",
            "Significant (p<0.05)": "Yes" if p < 0.05 else "No"
        })
anova_df = pd.DataFrame(anova_rows)
anova_df.to_csv("table3_anova.tsv", sep="\t", index=False)

# -----------------------------
# Plots
# -----------------------------
sns.set_style("white")

# Plot A: total average contamination per group
wide["Avg_Total"] = wide[avg_cols].sum(axis=1, skipna=True)
tot = (wide.groupby("Group", observed=True)["Avg_Total"]
       .mean().reindex(ORDER_GROUPS).reset_index())
fig, ax = plt.subplots(figsize=(5, 5), dpi=200)
sns.barplot(data=tot, x="Group", y="Avg_Total",
            order=ORDER_GROUPS, palette=PALETTE_GROUPS,
            edgecolor="black", ax=ax)
for i, r in tot.iterrows():
    ax.text(i, r["Avg_Total"]*1.01, f"{r['Avg_Total']:.1f}",
            ha="center", va="bottom", fontsize=9, weight="bold")
ax.set_xlabel("")
ax.set_ylabel("Mean total contamination (%)")
ax.set_xticklabels(ORDER_GROUPS, rotation=45, ha="right", fontsize=9)
style_axes(ax)
plt.tight_layout()
plt.savefig("plot_total_average_contamination_by_group.png", dpi=600, bbox_inches="tight")
plt.show()

# Plot B: breakdown of contaminants per group (stacked means of Avg_*)
stack = (wide.groupby("Group", observed=True)[avg_cols]
         .mean().reindex(ORDER_GROUPS))
stack = stack.rename(columns={
    "Avg_Human":"Human","Avg_Mouse":"Mouse","Avg_Vectors":"Vectors","Avg_Plasmodium":"Plasmodium"
})
ax = stack.plot(kind="bar", stacked=True, figsize=(6.2, 4.4), width=0.7,
                color=[PALETTE_CONTAM[k] for k in ["Human","Mouse","Vectors","Plasmodium"]],
                edgecolor="black")
ax.set_xlabel("")
ax.set_ylabel("Mean contamination by source (%)")
ax.set_xticklabels(ORDER_GROUPS, rotation=45, ha="right", fontsize=9)
ax.legend(title="", ncols=2, fontsize=9, loc="upper center", bbox_to_anchor=(0.5, 1.25))
style_axes(ax)
plt.tight_layout()
plt.savefig("plot_contamination_breakdown_stacked_by_group.png", dpi=600, bbox_inches="tight")
plt.show()

print("Done.")
print("Tables:")
print(" - table1_contamination_per_sample_wide.tsv")
print(" - table2_group_mean_sd.tsv")
print(" - table3_anova.tsv")
print("Plots:")
print(" - plot_total_average_contamination_by_group.png")
print(" - plot_contamination_breakdown_stacked_by_group.png")