# -*- coding: utf-8 -*-
"""MAG_quality_review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DeNU7belAu1DLgLaQzyHA3y3oiwWIqKf
"""

# all MAGS (Non-derep) with thick plot borders

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr, spearmanr

# ============================
# Load and Combine Datasets
# ============================

files = {
    "Public Transport": "checkm2_public_transport_final",
    "Hospital Environment": "checkm2_hosp_env",
    "Hospital Sewage": "checkm2_hosp_sewage_final",
    "Ambulance": "checkm2_ambulance_final"
}

dfs = []
for source, path in files.items():
    df = pd.read_csv(path, sep="\\t", engine='python')
    df["Sample_Source"] = source
    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)

# ✅ Standardize Sample_Source labels
label_map = {
    "Ambulance": "Ambulance",
    "Hospital Environment": "Hosp_env",
    "Hospital Sewage": "Hosp_sewage",
    "Public Transport": "Public_transp"
}
combined_df["Sample_Source"] = combined_df["Sample_Source"].replace(label_map)

# Save combined data
combined_df.to_csv("combined_checkm2_data.csv", index=False)

# Canonical order & palette
source_order = ["Ambulance", "Hosp_env", "Hosp_sewage", "Public_transp"]
palette = {
    "Public_transp": "#1f77b4",
    "Hosp_env": "#aec7e8",
    "Hosp_sewage": "#ff7f0e",
    "Ambulance": "#fdbf6f"
}

# ============================
# Classify MAGs by Quality
# ============================
def classify_quality(row):
    if row.get('Completeness', 0) >= 90 and row.get('Contamination', 100) <= 5:
        return 'High-quality'
    elif row.get('Completeness', 0) >= 50 and row.get('Contamination', 100) <= 10:
        return 'Medium-quality'
    else:
        return 'Low-quality'

combined_df["Quality_Tier"] = combined_df.apply(classify_quality, axis=1)

# ============================
# Utils
# ============================
def has_cols(df, cols):
    return all(c in df.columns for c in cols)

def style_axes(ax, spine_lw=2.8, tick_w=2.5):
    """Thick black axes and ticks, no grid."""
    ax.grid(False)
    ax.minorticks_on()
    for s in ax.spines.values():
        s.set_edgecolor("black")
        s.set_linewidth(spine_lw)
    ax.tick_params(which="both", width=tick_w)
    ax.tick_params(which="major", length=6)
    ax.tick_params(which="minor", length=3)

# ============================
# KDE Plots
# ============================
def plot_kde(metric, filename, xlabel):
    if metric not in combined_df.columns:
        print(f"[skip] {metric} not found.")
        return
    sns.set_style("whitegrid")
    fig, ax = plt.subplots(figsize=(5, 5))
    sns.kdeplot(
        data=combined_df,
        x=metric,
        hue="Sample_Source",
        hue_order=source_order,
        fill=True, alpha=0.5,
        linewidth=1.6,
        ax=ax, palette=palette
    )
    ax.set_xlabel(xlabel, fontsize=10, color='black')
    ax.set_ylabel("Density", fontsize=10, color='black')
    style_axes(ax)

    # keep legend but remove title
    leg = ax.get_legend()
    if leg is not None:
        leg.set_title("")

    plt.savefig(filename, dpi=600, bbox_inches="tight")
    plt.close()

plot_kde("Completeness", "completeness_distribution.png", "Completeness (%)")
plot_kde("Contamination", "contamination_distribution.png", "Contamination (%)")

# ============================
# Violin Plot
# ============================
def plot_violin(metric, ylabel, filename):
    if metric not in combined_df.columns:
        print(f"[skip] {metric} not found.")
        return
    sns.set_style("white")
    fig, ax = plt.subplots(figsize=(5, 5))
    sns.violinplot(
        data=combined_df,
        x="Sample_Source", y=metric,
        order=source_order,
        inner="point", scale="width",
        linewidth=1.8, palette=palette, ax=ax
    )
    ax.set_ylabel(ylabel, fontsize=10, color='black')
    ax.set_xlabel("", fontsize=10, color='black')
    plt.xticks(rotation=45)
    style_axes(ax)

    leg = ax.get_legend()
    if leg is not None:
        leg.set_title("")

    plt.savefig(filename, dpi=600, bbox_inches="tight")
    plt.close()

plot_violin("Coding_Density", "Coding Density", "coding_density_violin.png")

# ============================
# Scatter Plots
# ============================
def plot_scatter(x, y, xlabel, ylabel, filename):
    if not has_cols(combined_df, [x, y]):
        print(f"[skip] columns missing: {x}, {y}")
        return
    sns.set_style("white")
    fig, ax = plt.subplots(figsize=(5, 5))
    sns.scatterplot(
        data=combined_df, x=x, y=y,
        hue="Sample_Source", hue_order=source_order,
        palette=palette, alpha=0.7,
        edgecolor="black", linewidth=1.0, ax=ax
    )
    ax.set_xlabel(xlabel, fontsize=10, color='black')
    ax.set_ylabel(ylabel, fontsize=10, color='black')
    style_axes(ax)

    leg = ax.get_legend()
    if leg is not None:
        leg.set_title("")

    plt.savefig(filename, dpi=600, bbox_inches="tight")
    plt.close()

plot_scatter("GC_Content", "Genome_Size", "GC Content (%)", "Genome Size (bp)", "gc_vs_genome_size_scatter.png")
plot_scatter("Completeness", "Coding_Density", "Completeness (%)", "Coding Density", "completeness_vs_coding_density.png")
plot_scatter("Average_Gene_Length", "Total_Coding_Sequences", "Avg Gene Length (bp)", "Total Coding Sequences", "gene_length_vs_coding_sequences.png")

# ============================
# N50 vs Max Contig
# ============================
def plot_n50_vs_max_contig_with_global_trend():
    cols = ["Contig_N50", "Max_Contig_Length"]
    if not has_cols(combined_df, cols):
        print(f"[skip] columns missing: {cols}")
        return
    sns.set_style("white")
    fig, ax = plt.subplots(figsize=(5, 5))
    sns.scatterplot(
        data=combined_df,
        x="Contig_N50", y="Max_Contig_Length",
        hue="Sample_Source", hue_order=source_order,
        palette=palette, alpha=0.7,
        edgecolor="black", linewidth=1.0, ax=ax
    )
    sns.regplot(
        data=combined_df, x="Contig_N50", y="Max_Contig_Length",
        scatter=False, color="black",
        line_kws={"linewidth": 2.5, "linestyle": "--"},
        ax=ax
    )
    ax.set_xlabel("Contig N50 (bp)", fontsize=10, color='black')
    ax.set_ylabel("Max Contig Length (bp)", fontsize=10, color='black')
    style_axes(ax)

    leg = ax.get_legend()
    if leg is not None:
        leg.set_title("")

    plt.tight_layout()
    plt.savefig("n50_vs_max_contig_with_global_trend.png", dpi=600, bbox_inches="tight")
    plt.close()

plot_n50_vs_max_contig_with_global_trend()

# ============================
# GC% vs Genome Size — Density
# ============================
def plot_gc_vs_genomesize_density():
    cols = ["GC_Content", "Genome_Size"]
    if not has_cols(combined_df, cols):
        print(f"[skip] columns missing: {cols}")
        return
    sns.set_style("white")
    fig, ax = plt.subplots(figsize=(5, 5))
    sns.kdeplot(
        data=combined_df,
        x="GC_Content", y="Genome_Size",
        fill=True, cmap="viridis", levels=100, thresh=0.05, ax=ax
    )
    ax.set_xlabel("GC Content (%)", fontsize=10, color='black')
    ax.set_ylabel("Genome Size (bp)", fontsize=10, color='black')
    style_axes(ax)

    leg = ax.get_legend()
    if leg is not None:
        leg.set_title("")

    plt.tight_layout()
    plt.savefig("gc_vs_genome_size_density.png", dpi=600, bbox_inches="tight")
    plt.close()

plot_gc_vs_genomesize_density()

# ============================
# Correlation Analysis Table
# ============================
correlation_tests = [
    ("GC_Content", "Genome_Size"),
    ("Completeness", "Coding_Density"),
    ("Contig_N50", "Max_Contig_Length"),
    ("Average_Gene_Length", "Total_Coding_Sequences")
]

correlation_results = []
for x, y in correlation_tests:
    if not has_cols(combined_df, [x, y]):
        correlation_results.append({
            "Comparison": f"{x} vs {y}",
            "Pearson Correlation": None,
            "Pearson p-value": None,
            "Spearman Correlation": None,
            "Spearman p-value": None
        })
        continue
    df_clean = combined_df[[x, y]].dropna()
    if len(df_clean) < 3:
        correlation_results.append({
            "Comparison": f"{x} vs {y}",
            "Pearson Correlation": None,
            "Pearson p-value": None,
            "Spearman Correlation": None,
            "Spearman p-value": None
        })
        continue
    pearson_corr, pearson_p = pearsonr(df_clean[x], df_clean[y])
    spearman_corr, spearman_p = spearmanr(df_clean[x], df_clean[y])
    correlation_results.append({
        "Comparison": f"{x} vs {y}",
        "Pearson Correlation": round(pearson_corr, 3),
        "Pearson p-value": f"{pearson_p:.2e}",
        "Spearman Correlation": round(spearman_corr, 3),
        "Spearman p-value": f"{spearman_p:.2e}"
    })

correlation_df = pd.DataFrame(correlation_results)
correlation_df.to_csv("correlation_results.csv", index=False)

# ============================
# Stacked Bar Chart: MAG Quality by Source
# ============================
def plot_stacked_quality_bar():
    counts = (
        combined_df.groupby(["Sample_Source", "Quality_Tier"])
        .size()
        .unstack(fill_value=0)
    )
    tier_order = ["High-quality", "Medium-quality", "Low-quality"]
    for t in tier_order:
        if t not in counts.columns:
            counts[t] = 0
    counts = counts[tier_order]
    counts = counts.reindex(source_order).fillna(0).astype(int)

    ax = counts.plot(
        kind="bar", stacked=True, figsize=(5, 5),
        edgecolor="black", width=0.7,
        color=['#1b9e77', '#d95f02', '#7570b3']
    )
    ax.set_xlabel("")
    ax.set_ylabel("Number of MAGs")
    plt.xticks(rotation=45)
    ax.grid(False)

    legend_labels = ["High-quality", "Medium-quality", "Low-quality"]
    handles, _ = ax.get_legend_handles_labels()
    leg = ax.legend(handles, legend_labels, title="", fontsize=8, title_fontsize=9, loc="best", frameon=True)
    if leg is not None:
        leg.set_title("")

    style_axes(ax)

    for i, (src, row) in enumerate(counts.iterrows()):
        total = int(row.sum())
        ax.text(i, total + max(1, total*0.01), str(total), ha='center', va='bottom', fontsize=8, weight='bold')

    plt.tight_layout()
    plt.savefig("quality_tier_stacked_bar.png", dpi=600)
    plt.close()

plot_stacked_quality_bar()

# ============================
# Tables (CSV outputs)
# ============================
quality_tier_table = (
    combined_df.groupby(["Sample_Source", "Quality_Tier"])
    .size().reset_index(name="MAG_Count")
    .pivot(index="Sample_Source", columns="Quality_Tier", values="MAG_Count")
    .reindex(source_order)
    .fillna(0).astype(int).reset_index()
)
quality_tier_table.to_csv("quality_tier_per_environment_table.csv", index=False)

high_quality_bins = combined_df[combined_df["Quality_Tier"] == "High-quality"].copy()
high_quality_bins.to_csv("high_quality_bins.csv", index=False)

summary_stats = combined_df.groupby("Sample_Source").agg({
    "Completeness": ["mean", "median", "std", "min", "max"],
    "Contamination": ["mean", "median", "std", "min", "max"],
    "Genome_Size": ["mean", "median", "std", "min", "max"],
    "GC_Content": ["mean", "median", "std", "min", "max"],
    "Coding_Density": ["mean", "median", "std", "min", "max"]
})
summary_stats.columns = ['_'.join(col) for col in summary_stats.columns]
summary_stats = summary_stats.reindex(source_order).reset_index()
summary_stats.to_csv("summary_stats_by_source.csv", index=False)

## This is for the dereplicated bins file processing
# You need the genomeInformation file from the global derep, then a list of the dereplicated .fa files (from derep_genomes) all pre-processed manually before the following matching processing

import pandas as pd

# ================================
# File Paths (adjust if needed)
# ================================
dereplicated_path = "dereplicated"
genome_info_path = "genomeInformation_global.csv"
output_path = "merged_dereplicated_with_genome_info.csv"

# ================================
# Load Files
# ================================
dereplicated_df = pd.read_csv(dereplicated_path)
genome_info_df = pd.read_csv(genome_info_path)

# ================================
# Clean & Merge
# ================================
# Strip whitespace just in case
dereplicated_df['Sample_ID'] = dereplicated_df['Sample_ID'].astype(str).str.strip()
dereplicated_df['Bins'] = dereplicated_df['Bins'].astype(str).str.strip()

genome_info_df['Sample_ID'] = genome_info_df['Sample_ID'].astype(str).str.strip()
genome_info_df['Bins'] = genome_info_df['Bins'].astype(str).str.strip()

# Merge on Sample_ID and Bins
merged_df = pd.merge(
    dereplicated_df,
    genome_info_df[['Sample_ID', 'Bins', 'length', 'N50', 'centrality']],
    on=['Sample_ID', 'Bins'],
    how='left'
)

# ================================
# Report Summary
# ================================
matched = merged_df['length'].notna().sum()
unmatched = merged_df['length'].isna().sum()
print(f"Matched rows: {matched}")
print(f" Unmatched rows: {unmatched}")

# ================================
# Save Output
# ================================
merged_df.to_csv(output_path, index=False)
print(f"Merged file saved as: {output_path}")
##NB: Check the file and correct the names of the group if necessary before the next step. It should match the group names in the checkm2_combined file

# Merge derep bins info with checkm2 metrics

import pandas as pd

# File paths
checkm2_path = "combined_checkm2_data.csv"
derep_path = "/content/merged_dereplicated_with_genome_info.csv"

# Load data
checkm2_df = pd.read_csv(checkm2_path)
derep_df = pd.read_csv(derep_path)

# Clean column names
checkm2_df.columns = checkm2_df.columns.str.strip()
derep_df.columns = derep_df.columns.str.strip()

# Extract Bin_ID more flexibly: bin.4, bin_4 etc.
checkm2_df["Bin_ID"] = checkm2_df["Name"].astype(str).str.extract(r"(bin[._]?\d+)")

# Extract Sample_ID flexibly: SRR, ERR, DRR IDs
checkm2_df["Sample_ID_extracted"] = checkm2_df["Name"].astype(str).str.extract(r"((?:SRR|ERR|DRR)\d+)")

# Clean dereplicated bins (remove .fa if present)
derep_df["Bins"] = derep_df["Bins"].astype(str).str.replace(".fa$", "", regex=True)

# Merge on Sample_ID + Bin
merged = pd.merge(
    derep_df,
    checkm2_df[
        [
            "Sample_ID_extracted", "Bin_ID",
            "Completeness", "Contamination",
            "Completeness_Model_Used", "Translation_Table_Used",
            "Coding_Density", "Contig_N50", "Average_Gene_Length",
            "Genome_Size", "GC_Content", "Total_Coding_Sequences",
            "Total_Contigs", "Max_Contig_Length"
        ]
    ],
    left_on=["Sample_ID", "Bins"],
    right_on=["Sample_ID_extracted", "Bin_ID"],
    how="left"
).drop(columns=["Sample_ID_extracted", "Bin_ID"])

# Save new merged file
output_path = "dereplicated_with_checkm2_metrics.csv"
merged.to_csv(output_path, index=False)

# Report
print(f"✅ Merged file saved: {output_path}")
print(f"Matched rows: {(~merged['Completeness'].isna()).sum()}")
print(f"Unmatched rows: {merged['Completeness'].isna().sum()}")

# Preview
merged.head(20)
##Correct the group names of the output files before next step

# Derep MAG analysis, thick borders per plot

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr, spearmanr

# ============================
# Load file
# ============================
df = pd.read_csv("/content/dereplicated_with_checkm2_metrics.csv")

# ============================
# Classify MAGs by Quality
# ============================
def classify_quality(row):
    if row.get('Completeness', 0) >= 90 and row.get('Contamination', 100) <= 5:
        return 'High-quality'
    elif row.get('Completeness', 0) >= 50 and row.get('Contamination', 100) <= 10:
        return 'Medium-quality'
    else:
        return 'Low-quality'

df["Quality_Tier"] = df.apply(classify_quality, axis=1)

# ============================
# Palette and order
# ============================
# Handle either Public_transp or Public_transport gracefully
palette = {
    "Ambulance": "#fdbf6f",
    "Hosp_env": "#aec7e8",
    "Hosp_sewage": "#ff7f0e",
    "Public_transp": "#1f77b4",
    "Public_transport": "#1f77b4"
}
source_order = ["Ambulance", "Hosp_env", "Hosp_sewage", "Public_transport", "Public_transp"]
present_groups = [g for g in source_order if "Group" in df.columns and g in df["Group"].unique()]

# ============================
# Per-plot border thickening
# ============================
def thicken_axes(ax, lw=2.8, tickw=2.2):
    for s in ax.spines.values():
        s.set_linewidth(lw)
    ax.tick_params(width=tickw)

# ============================
# KDE Plots
# ============================
def plot_kde(metric, filename, xlabel):
    if metric not in df.columns or "Group" not in df.columns or len(present_groups) == 0:
        print(f"[skip] {metric} missing or no Group values present.")
        return
    plt.figure(figsize=(5,5))
    ax = sns.kdeplot(
        data=df, x=metric, hue="Group",
        hue_order=present_groups, palette=palette,
        fill=True, alpha=0.5, linewidth=2.0
    )
    thicken_axes(ax)
    plt.xlabel(xlabel); plt.ylabel("Density")
    leg = plt.gca().get_legend()
    if leg is not None:
        leg.set_title("")
    plt.tight_layout()
    plt.savefig(filename, dpi=600, bbox_inches="tight")
    plt.show()

plot_kde("Completeness", "completeness_distribution.png", "Completeness (%)")
plot_kde("Contamination", "contamination_distribution.png", "Contamination (%)")

# ============================
# Scatter Plots
# ============================
def plot_scatter(x, y, xlabel, ylabel, filename):
    if not all(c in df.columns for c in [x,y]) or "Group" not in df.columns or len(present_groups) == 0:
        print(f"[skip] {x}, {y} missing or no Group values present.")
        return
    plt.figure(figsize=(5,5))
    ax = sns.scatterplot(
        data=df, x=x, y=y, hue="Group",
        hue_order=present_groups, palette=palette,
        alpha=0.7, edgecolor="black", linewidth=0.8
    )
    thicken_axes(ax)
    plt.xlabel(xlabel); plt.ylabel(ylabel)
    leg = plt.gca().get_legend()
    if leg is not None:
        leg.set_title("")
    plt.tight_layout()
    plt.savefig(filename, dpi=600, bbox_inches="tight")
    plt.show()

plot_scatter("GC_Content","Genome_Size","GC Content","Genome Size","gc_vs_genome_size.png")
plot_scatter("Completeness","Coding_Density","Completeness","Coding Density","completeness_vs_coding_density.png")
plot_scatter("Average_Gene_Length","Total_Coding_Sequences","Avg Gene Length","Total CDS","gene_length_vs_coding_sequences.png")

# ============================
# Number of Bins per Environment
# ============================
if "Group" in df.columns and len(present_groups) > 0:
    bin_counts = df["Group"].value_counts().reindex(present_groups).fillna(0).astype(int)

    plt.figure(figsize=(6,6))
    ax = sns.barplot(x=bin_counts.index, y=bin_counts.values,
                     palette={k: palette[k] for k in bin_counts.index}, order=bin_counts.index,
                     edgecolor="black")
    thicken_axes(ax)
    plt.ylabel("Number of Bins")
    plt.xlabel("Environment")
    plt.title("Number of Bins per Environment")
    plt.xticks(rotation=45)

    for i, val in enumerate(bin_counts.values):
        ax.text(i, val + max(bin_counts.values)*0.01, str(val),
                ha='center', va='bottom', fontsize=10, fontweight="bold")

    plt.tight_layout()
    plt.savefig("bin_counts_per_environment.png", dpi=600, bbox_inches="tight")
    plt.show()
else:
    print("[skip] No Group column or groups present, bin count plot skipped.")

# ============================
# Summary Tables
# ============================
if "Group" in df.columns:
    # 1. Quality tier per environment
    quality_tier_table = (
        df.groupby(["Group","Quality_Tier"]).size().reset_index(name="MAG_Count")
        .pivot(index="Group", columns="Quality_Tier", values="MAG_Count")
        .reindex(present_groups).fillna(0).astype(int).reset_index()
    )
    quality_tier_table.to_csv("quality_tier_per_environment_table.csv", index=False)

    # 2. Summary stats per environment
    summary_stats = df.groupby("Group").agg({
        "Completeness": ["mean","median","std","min","max"],
        "Contamination": ["mean","median","std","min","max"],
        "Genome_Size": ["mean","median","std","min","max"],
        "GC_Content": ["mean","median","std","min","max"],
        "Coding_Density": ["mean","median","std","min","max"]
    })
    summary_stats.columns = ['_'.join(col) for col in summary_stats.columns]
    summary_stats.to_csv("summary_stats_by_source.csv")
else:
    print("[note] Group column missing, skipped group-wise tables.")

# ============================
# Correlation Analysis Table
# ============================
correlation_tests = [
    ("GC_Content", "Genome_Size"),
    ("Completeness", "Coding_Density"),
    ("Contig_N50", "Max_Contig_Length"),
    ("Average_Gene_Length", "Total_Coding_Sequences")
]

correlation_results = []
for x, y in correlation_tests:
    if not all(c in df.columns for c in [x, y]):
        correlation_results.append({
            "Comparison": f"{x} vs {y}",
            "Pearson Correlation": None,
            "Pearson p-value": None,
            "Spearman Correlation": None,
            "Spearman p-value": None
        })
        continue
    # force numeric, drop NA
    df_clean = df[[x, y]].apply(pd.to_numeric, errors="coerce").dropna()
    if len(df_clean) < 3:
        correlation_results.append({
            "Comparison": f"{x} vs {y}",
            "Pearson Correlation": None,
            "Pearson p-value": None,
            "Spearman Correlation": None,
            "Spearman p-value": None
        })
        continue
    pearson_corr, pearson_p = pearsonr(df_clean[x], df_clean[y])
    spearman_corr, spearman_p = spearmanr(df_clean[x], df_clean[y])
    correlation_results.append({
        "Comparison": f"{x} vs {y}",
        "Pearson Correlation": round(pearson_corr, 3),
        "Pearson p-value": f"{pearson_p:.2e}",
        "Spearman Correlation": round(spearman_corr, 3),
        "Spearman p-value": f"{spearman_p:.2e}"
    })

correlation_df = pd.DataFrame(correlation_results)
correlation_df.to_csv("correlation_results.csv", index=False)