# -*- coding: utf-8 -*-
"""Quast_review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11B0Tb8sQCsJSJJy3JjX1hxpP1PyhNb9n
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats
import matplotlib.ticker as mticker

# ============================
# Load and Combine QUAST Files
# ============================
simplified_files = {
    "Ambulance": "quast_Simplified_ambulance_final",
    "Hospital Environment": "quast_Simplified_hosp_env",
    "Hospital Sewage": "quast_Simplified_hosp_sewage",
    "Public Transport": "quast_Simplified_final_public_transp"
}

filtered_files = {
    "Ambulance": "quast_filtered_ambulance_final",
    "Hospital Environment": "quast_filtered_hosp_env",
    "Hospital Sewage": "quast_filtered_hosp_sewage",
    "Public Transport": "quast_filtered_final_public_transp"
}

def load_quast_files(file_dict, filter_status):
    dfs = []
    for category, path in file_dict.items():
        df = pd.read_csv(path, sep='\\t', engine='python')
        df["Category"] = category
        df["Filter_Status"] = filter_status
        dfs.append(df)
    return dfs

dfs_simplified = load_quast_files(simplified_files, "Simplified")
dfs_filtered   = load_quast_files(filtered_files, "Filtered")

df = pd.concat(dfs_simplified + dfs_filtered, ignore_index=True)
df.columns = df.columns.str.strip()

numeric_cols = ['# contigs', 'Largest contig', 'Total length', 'GC (%)',
                'N50', 'N75', 'L50', 'L75', "# N's per 100 kbp"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df.dropna(subset=numeric_cols, inplace=True)

# ============================
# Save merged QUAST tables
# ============================
out_cols = ['Category', 'Filter_Status'] + [c for c in df.columns if c not in ['Category', 'Filter_Status']]
df[df['Filter_Status']=='Simplified'][out_cols].to_csv("quast_merged_simplified.tsv", sep="\t", index=False)
df[df['Filter_Status']=='Filtered'][out_cols].to_csv("quast_merged_filtered.tsv",  sep="\t", index=False)
df[out_cols].to_csv("quast_merged_all.tsv", sep="\t", index=False)

# ============================
# Rename categories and palette
# ============================
label_map = {
    "Ambulance": "Ambulance",
    "Hospital Environment": "Hosp_env",
    "Hospital Sewage": "Hosp_sewage",
    "Public Transport": "Public_transp"
}
df["Category"] = df["Category"].map(label_map)

custom_palette = {
    "Public_transp": "#1f77b4",
    "Hosp_env": "#aec7e8",
    "Hosp_sewage": "#ff7f0e",
    "Ambulance": "#fdbf6f"
}
category_order = ["Ambulance", "Hosp_env", "Hosp_sewage", "Public_transp"]

# ============================
# QUAST metrics boxplots, log scale
# ============================
def plot_quast_metrics(subset_df, status_label, use_log10_values=False):
    metrics_to_plot = ['N50', '# contigs', 'L50', 'Total length']
    fig, axes = plt.subplots(2, 2, figsize=(5, 5))
    axes = axes.flatten()

    for i, metric in enumerate(metrics_to_plot):
        ax = axes[i]
        sd = subset_df[subset_df[metric] > 0].copy()
        if sd.empty:
            ax.text(0.5, 0.5, f'No positive values for {metric}', ha='center', va='center')
            ax.axis('off')
            continue

        if use_log10_values:
            ycol = f'log10_{metric}'
            sd[ycol] = np.log10(sd[metric])
            sns.boxplot(
                data=sd, x='Category', y=ycol,
                palette=custom_palette, order=category_order, ax=ax
            )
            ax.set_ylabel(f'log10 {metric}', fontsize=10)
            ax.yaxis.set_major_locator(mticker.MaxNLocator(nbins=6))
        else:
            sns.boxplot(
                data=sd, x='Category', y=metric,
                palette=custom_palette, order=category_order, ax=ax
            )
            ax.set_ylabel(f'{metric}', fontsize=10)
            ax.set_yscale('log')
            ax.yaxis.set_major_locator(mticker.LogLocator(base=10))
            ax.yaxis.set_minor_locator(mticker.LogLocator(base=10, subs=np.arange(2, 10) * 0.1))
            ax.yaxis.set_minor_formatter(mticker.NullFormatter())

        ax.set_xlabel('')
        ax.set_xticklabels(category_order, rotation=45, ha='right', fontsize=9)
        for s in ax.spines.values():
            s.set_edgecolor("black")
            s.set_linewidth(1.8)

    plt.tight_layout()
    plt.savefig(f"Quast_boxplots_{status_label}.png", dpi=600)
    plt.show()

# ============================
# N50 vs # Contigs, log-safe
# ============================
def plot_n50_vs_contigs(subset_df, status_label):
    sd = subset_df[subset_df['# contigs'] > 0].copy()
    if sd.empty:
        print(f"[skip] No positive # contigs for {status_label}")
        return

    plt.figure(figsize=(4, 4))
    plt.xscale("log")

    sns.scatterplot(
        data=sd, x='# contigs', y='N50',
        hue='Category', hue_order=category_order,
        palette=custom_palette, alpha=0.6, s=30,
        edgecolor='black', linewidth=0.7
    )

    sns.regplot(
        data=sd, x='# contigs', y='N50',
        scatter=False, color='black', logx=True,
        line_kws={'linewidth': 2.0, 'linestyle': '--'}
    )

    # R^2 on log10 x
    x_log = np.log10(sd['# contigs'])
    r_value = stats.linregress(x_log, sd['N50']).rvalue
    plt.text(0.95, 0.93, f'R² = {r_value**2:.2f}', transform=plt.gca().transAxes,
             fontsize=8, ha='right', bbox=dict(facecolor='white', alpha=0.1))

    plt.xlabel('Number of Contigs', fontsize=10)
    plt.ylabel('N50', fontsize=10)
    plt.legend(title="", fontsize=7, frameon=True, loc='center', bbox_to_anchor=(0.74, 0.80))

    ax = plt.gca()
    for s in ax.spines.values():
        s.set_linewidth(1.8)

    plt.tight_layout()
    plt.savefig(f"n50_vs_contigs_{status_label}.png", dpi=600)
    plt.show()

# ============================
# GC% vs N50 scatter, N50 on log scale
# ============================
def plot_gc_vs_n50_scatter(subset_df, status_label):
    sd = subset_df[subset_df['N50'] > 0].copy()
    if sd.empty:
        print(f"[skip] No positive N50 values for {status_label}")
        return

    plt.figure(figsize=(4, 4))

    ax = sns.scatterplot(
        data=sd, x='GC (%)', y='N50',
        hue='Category', hue_order=category_order,
        palette=custom_palette, alpha=0.7, s=28,
        edgecolor='black', linewidth=0.7
    )
    ax.set_yscale('log')

    ax.set_xlabel('GC Content (%)', fontsize=10)
    ax.set_ylabel('N50', fontsize=10)

    # clean legend
    leg = ax.get_legend()
    if leg is not None:
        leg.set_title("")

    # thick frame
    for s in ax.spines.values():
        s.set_linewidth(1.8)

    plt.tight_layout()
    plt.savefig(f"gc_vs_n50_scatter_{status_label}.png", dpi=600)
    plt.show()

# ============================
# Run for Filtered and Simplified
# ============================
df_filtered   = df[df['Filter_Status'] == 'Filtered']
df_simplified = df[df['Filter_Status'] == 'Simplified']

# Boxplots on log10 y-axis, set use_log10_values=True if you prefer log10 values
plot_quast_metrics(df_filtered,   "Filtered",   use_log10_values=False)
plot_quast_metrics(df_simplified, "Simplified", use_log10_values=False)

plot_n50_vs_contigs(df_filtered, "Filtered")
plot_n50_vs_contigs(df_simplified, "Simplified")

# New scatter replacing the density plot
plot_gc_vs_n50_scatter(df_filtered, "Filtered")
plot_gc_vs_n50_scatter(df_simplified, "Simplified")