# -*- coding: utf-8 -*-
"""Runtime_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFJXPdG0zF35uuhiPtexQdOU5ED8rDGy
"""

# ============================
# Runtime Analysis of MAG Pipeline
# ============================

import pandas as pd

# ============================
# File paths (upload first with files.upload() in Colab)
# ============================
files = {
    "Ambulance": "merged_runtime_ambulance",
    "Hosp_env": "merged_runtime_hosp_env",
    "Hosp_sewage": "merged_runtime_hosp_sewage",
    "Public_transport": "merged_runtime_public_transport",
    "Global": "global_runtime_taxonomy_arg_vfdb"
}

all_stepwise = []

# ============================
# Per-environment summaries
# ============================
for env, path in files.items():
    df = pd.read_csv(path, sep=",", engine="python")

    # Ensure numeric conversion
    for col in ["Duration_sec", "Threads", "Mem_GB", "InputSize", "OutputSize"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # Summarize per step
    step_summary = (
        df.groupby("Step")
        .agg(
            Runs=("Duration_sec","count"),
            Mean_sec=("Duration_sec","mean"),
            Std_sec=("Duration_sec","std"),
            Mean_threads=("Threads","mean"),
            Mean_ram=("Mem_GB","mean"),
            Mean_input=("InputSize","mean"),
            Mean_output=("OutputSize","mean")
        )
        .reset_index()
    )
    step_summary["Environment"] = env
    # Convert runtime to minutes
    step_summary["Mean_min"] = (step_summary["Mean_sec"]/60).round(2)
    step_summary["Std_min"] = (step_summary["Std_sec"]/60).round(2)
    all_stepwise.append(step_summary)

# Combine all environment results
summary_clean = pd.concat(all_stepwise, ignore_index=True)

# Format runtime as "mean ± sd"
summary_clean["Runtime_min"] = summary_clean["Mean_min"].astype(str) + " ± " + summary_clean["Std_min"].astype(str)

# Final per-environment table
final_summary = summary_clean[[
    "Environment","Step","Runs","Runtime_min",
    "Mean_threads","Mean_ram","Mean_input","Mean_output"
]]

print("✅ Per-environment Stepwise Summary")
display(final_summary)

# ============================
# Global summary across environments
# ============================
global_summary = (
    summary_clean.groupby("Step")[["Runs","Mean_sec","Std_sec","Mean_threads","Mean_ram","Mean_input","Mean_output"]]
    .mean()
    .reset_index()
)

# Convert runtime to minutes with SD
global_summary["Mean_min"] = (global_summary["Mean_sec"]/60).round(2)
global_summary["Std_min"] = (global_summary["Std_sec"]/60).round(2)
global_summary["Runtime_min"] = global_summary["Mean_min"].astype(str) + " ± " + global_summary["Std_min"].astype(str)

# Final global table
global_final = global_summary[[
    "Step","Runs","Runtime_min","Mean_threads","Mean_ram","Mean_input","Mean_output"
]]

print("✅ Global Stepwise Summary")
display(global_final)

# ============================
# Save outputs for reviewers
# ============================
final_summary.to_csv("stepwise_runtime_per_environment.csv", index=False)
global_final.to_csv("stepwise_runtime_global.csv", index=False)

print("📂 Saved: stepwise_runtime_per_environment.csv and stepwise_runtime_global.csv")