# -*- coding: utf-8 -*-
"""First_ML_PART1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3fg9AxNVsDffvz9xFyFB9kzyQjqj6i8
"""

# ===============================
# Step 1. Data Preparation
# ===============================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# -------------------------
# Load data
# -------------------------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)
meta = pd.read_csv("Merged_metadata_all.csv")

# Align samples
common_samples = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common_samples]
meta = meta[meta["Sample_ID"].isin(common_samples)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]   # enforce same order

# Features and labels
X = tpm.T.values                      # samples × species
y = meta["Group"].values              # environment labels

print("Features shape (samples × species):", X.shape)
print("Labels distribution:\n", meta["Group"].value_counts())

# -------------------------
# Split: 80% train, 20% hold-out
# -------------------------
X_train, X_hold, y_train, y_hold = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print("\n Train size:", X_train.shape[0], "Hold-out size:", X_hold.shape[0])
print("Train label distribution:\n", pd.Series(y_train).value_counts())
print("Hold-out label distribution:\n", pd.Series(y_hold).value_counts())

# ===============================
# Benchmarking with mean ± SD (Nature-style)
# ===============================

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, accuracy_score, balanced_accuracy_score, f1_score, cohen_kappa_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# -------------------------
# Define scorers
# -------------------------
scorers = {
    "accuracy": make_scorer(accuracy_score),
    "balanced_accuracy": make_scorer(balanced_accuracy_score),
    "f1_macro": make_scorer(f1_score, average="macro"),
    "kappa": make_scorer(cohen_kappa_score)
}

# -------------------------
# Define models
# -------------------------
models = {
    "DecisionTree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    "RandomForest": RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced"),
    "LogisticRegression": LogisticRegression(max_iter=5000, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel="rbf", probability=True, random_state=42, class_weight="balanced"),
    "GradientBoosting": GradientBoostingClassifier(random_state=42)
}

# -------------------------
# Cross-validation (10-fold)
# -------------------------
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
results = []

for name, model in models.items():
    cv_out = cross_validate(model, X_train, y_train, cv=cv, scoring=scorers, n_jobs=-1, return_estimator=False)

    # Store mean + std for each metric
    for metric in scorers.keys():
        values = cv_out[f"test_{metric}"]
        results.append({
            "Model": name,
            "Metric": metric,
            "Mean": np.mean(values),
            "SD": np.std(values)
        })

df_results = pd.DataFrame(results)
print("\n Benchmarking results (mean ± SD across folds):")
print(df_results)

# Save table
df_results.to_csv("ML_Benchmarking_AllModels_1.csv", index=False)

# ===============================
# Benchmarking Statistics Figure
# ===============================

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

# Sort metrics for consistent order
metric_order = ["Accuracy", "Balanced Accuracy", "F1 Macro", "Kappa"]

# Prepare plotting
sns.set_theme(style="white", context="talk")

g = sns.catplot(
    data=df_results,
    x="Mean", y="Model",
    col="Metric", col_wrap=2,
    kind="point", join=False,
    errorbar=None, dodge=True,
    palette="Set2",
    height=4.5, aspect=1.3
)

# Add custom error bars & formatting
for ax, metric in zip(g.axes.flat, metric_order):
    sub = df_results[df_results["Metric"]==metric]
    for i, row in sub.iterrows():
        ax.errorbar(
            row["Mean"], row["Model"],
            xerr=row["SD"],
            fmt='o', color="black", capsize=3
        )

    # Clean aesthetics
    ax.grid(False)
    for spine in ax.spines.values():
        spine.set_edgecolor("black")
        spine.set_linewidth(1)

    # Alternate shading for rows (highlight readability)
    for ytick, label in enumerate(sub["Model"].unique()):
        if ytick % 2 == 0:
            ax.axhspan(ytick-0.4, ytick+0.4, facecolor="lightgrey", alpha=0.2, zorder=0)

    ax.set_xlim(0.85, 1.0)
    ax.set_xlabel("Score (mean ± SD)", fontsize=12)
    ax.set_ylabel("")
    ax.set_title(metric, fontsize=14, weight="bold")

plt.suptitle("", fontsize=18, weight="bold", y=1.05)
plt.tight_layout()
plt.savefig("ML_Benchmarking_1.tiff", dpi=600, bbox_inches="tight")
plt.show()


# Open the saved TIFF image using Pillow
img = Image.open("ML_Benchmarking_1.tiff")

# Save the image again with LZW compression
img.save("ML_Benchmarking_2_compressed.tiff", compression="lzw")

print("Compressed image saved as ML_Benchmarking_1_compressed.tiff")

# ===============================
# Benchmarking Statistics Table
# ===============================

# Pivot for table
table = df_results.pivot(index="Model", columns="Metric", values="Mean")
table_sd = df_results.pivot(index="Model", columns="Metric", values="SD")

# Combine mean ± SD into one string
stats_table = table.round(3).astype(str) + " ± " + table_sd.round(3).astype(str)

# Save clean table
stats_table.to_csv("ML_Benchmarking_Statistics_2.csv")
print(stats_table)

# ===============================
# Statistical Comparisons of Models ==== Fold_Level (This is important if you want to conduct some statistical Comparisons)
# ===============================

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, accuracy_score, balanced_accuracy_score, f1_score, cohen_kappa_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from scipy.stats import friedmanchisquare, wilcoxon
import scikit_posthocs as sp
import seaborn as sns
import matplotlib.pyplot as plt

# -------------------------
# 1. Setup scorers & models
# -------------------------
scorers = {
    "accuracy": make_scorer(accuracy_score),
    "balanced_accuracy": make_scorer(balanced_accuracy_score),
    "f1_macro": make_scorer(f1_score, average="macro"),
    "kappa": make_scorer(cohen_kappa_score)
}

models = {
    "DecisionTree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    "RandomForest": RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced"),
    "LogisticRegression": LogisticRegression(max_iter=5000, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel="rbf", probability=True, random_state=42, class_weight="balanced"),
    "GradientBoosting": GradientBoostingClassifier(random_state=42)
}

# -------------------------
# 2. Collect fold-level results
# -------------------------
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
fold_results = []

for name, model in models.items():
    cv_out = cross_validate(model, X_train, y_train, cv=cv, scoring=scorers, n_jobs=-1, return_estimator=False)
    for metric in scorers.keys():
        for v in cv_out[f"test_{metric}"]:
            fold_results.append({"Model": name, "Metric": metric, "Score": v})

df_folds = pd.DataFrame(fold_results)
df_folds.to_csv("ML_Benchmarking_FoldLevel.csv", index=False)
print("Saved fold-level benchmarking results")

# -------------------------
# 3. Friedman test (global across models for each metric)
# -------------------------
friedman_results = {}
for metric in scorers.keys():
    pivot = df_folds[df_folds["Metric"]==metric].pivot(columns="Model", values="Score")
    stat, p = friedmanchisquare(*[pivot[m].dropna() for m in pivot.columns])
    friedman_results[metric] = {"stat": stat, "p": p}

friedman_df = pd.DataFrame(friedman_results).T
friedman_df.to_csv("ML_FriedmanTest.csv")
print("\n Friedman tests:\n", friedman_df)

# -------------------------
# 4. Pairwise Wilcoxon tests (Holm correction) === continue with this step only if you found atleast 1 difference in the Friedman test
# -------------------------
pairwise_results = []
for metric in scorers.keys():
    pivot = df_folds[df_folds["Metric"]==metric].pivot(columns="Model", values="Score")
    models_list = pivot.columns.tolist()
    for i in range(len(models_list)):
        for j in range(i+1, len(models_list)):
            m1, m2 = models_list[i], models_list[j]
            stat, p = wilcoxon(pivot[m1], pivot[m2])
            pairwise_results.append({"Metric": metric, "Model1": m1, "Model2": m2, "p_raw": p})

df_pairwise = pd.DataFrame(pairwise_results)

# Holm-Bonferroni correction
df_pairwise["p_adj"] = df_pairwise.groupby("Metric")["p_raw"].transform(lambda x: np.minimum(1, x * len(x)))
df_pairwise.to_csv("ML_Pairwise_Wilcoxon.csv", index=False)
print("\n Pairwise Wilcoxon with Holm correction:\n", df_pairwise.head())

# -------------------------
# 5. Critical Difference (CD) diagram (Nemenyi posthoc)
# -------------------------
for metric in scorers.keys():
    pivot = df_folds[df_folds["Metric"]==metric].pivot(columns="Model", values="Score")
    nemenyi = sp.posthoc_nemenyi_friedman(pivot.values)
    nemenyi.index, nemenyi.columns = pivot.columns, pivot.columns
    nemenyi.to_csv(f"ML_Nemenyi_{metric}.csv")

    plt.figure(figsize=(12,8))
    sns.heatmap(nemenyi, annot=True, fmt=".3f", cmap="coolwarm", cbar_kws={"label":"p-value"})
    plt.title(f"Posthoc Nemenyi test — {metric}")
    plt.tight_layout()
    plt.savefig(f"ML_NemenyiHeatmap_{metric}.tiff", dpi=600)
    plt.close()

# ===============================
#  Nested CV + Holdout (DecisionTree & RandomForest)
# ===============================

import numpy as np
import pandas as pd
from collections import defaultdict

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.metrics import (accuracy_score, balanced_accuracy_score, f1_score,
                             cohen_kappa_score, classification_report, confusion_matrix)
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# -------------------------
# 1. Load CLR batch-corrected features + metadata
# -------------------------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)  # species x samples
meta = pd.read_csv("Merged_metadata_all.csv")

# Align sample IDs
common_samples = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common_samples]
meta = meta[meta["Sample_ID"].isin(common_samples)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]   # enforce same order

X = tpm.T.values
y = meta["Group"].values

#print("Features shape (samples x species):", X.shape)
#print("Labels distribution:\n", pd.Series(y).value_counts())

# -------------------------
# 2. Train/test split (hold-out 20%)
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

#print("\n✅ Train size:", X_train.shape[0], "Hold-out size:", X_test.shape[0])
#print("Train label distribution:\n", pd.Series(y_train).value_counts())
#print("Hold-out label distribution:\n", pd.Series(y_test).value_counts())

# -------------------------
# 3. Models + param grids
# -------------------------
models = {
    "DecisionTree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
    "RandomForest": RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced")
}

param_grids = {
    "DecisionTree": {
        "max_depth": [None, 5, 10],
        "min_samples_leaf": [1, 3, 5],
        "min_samples_split": [2, 5, 10]
    },
    "RandomForest": {
        "n_estimators": [200, 500],
        "max_depth": [None, 10, 20],
        "min_samples_leaf": [1, 3, 5],
        "max_features": ["sqrt", 0.3, 0.5]
    }
}

outer = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
inner = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

cv_summary, fold_dfs, best_params = [], [], {}

# -------------------------
# 4. Nested CV
# -------------------------
for name, base_model in models.items():
    outer_metrics = defaultdict(list)

    for fold, (tr_idx, te_idx) in enumerate(outer.split(X_train, y_train), 1):
        X_tr, X_te = X_train[tr_idx], X_train[te_idx]
        y_tr, y_te = y_train[tr_idx], y_train[te_idx]

        gs = GridSearchCV(
            base_model, param_grids[name], cv=inner,
            scoring="balanced_accuracy", n_jobs=-1
        )
        gs.fit(X_tr, y_tr)

        best = gs.best_estimator_
        y_pred = best.predict(X_te)

        # record fold metrics
        acc = accuracy_score(y_te, y_pred)
        bacc = balanced_accuracy_score(y_te, y_pred)
        f1 = f1_score(y_te, y_pred, average="macro")
        kappa = cohen_kappa_score(y_te, y_pred)

        outer_metrics["Accuracy"].append(acc)
        outer_metrics["BalancedAcc"].append(bacc)
        outer_metrics["F1_macro"].append(f1)
        outer_metrics["Kappa"].append(kappa)

        fold_dfs.append(pd.DataFrame({
            "Model": [name],
            "Fold": [fold],
            "Accuracy": [acc],
            "BalancedAcc": [bacc],
            "F1_macro": [f1],
            "Kappa": [kappa]
        }))

    # mean across outer folds
    cv_summary.append({
        "Model": name,
        "MeanAcc": np.mean(outer_metrics["Accuracy"]),
        "StdAcc": np.std(outer_metrics["Accuracy"]),
        "MeanBalancedAcc": np.mean(outer_metrics["BalancedAcc"]),
        "StdBalancedAcc": np.std(outer_metrics["BalancedAcc"]),
        "MeanF1": np.mean(outer_metrics["F1_macro"]),
        "MeanKappa": np.mean(outer_metrics["Kappa"])
    })

    # final best params from full training
    gs_full = GridSearchCV(
        base_model, param_grids[name], cv=inner,
        scoring="balanced_accuracy", n_jobs=-1
    )
    gs_full.fit(X_train, y_train)
    best_params[name] = gs_full.best_params_

# -------------------------
# 5. Save CV results
# -------------------------
cv_df = pd.DataFrame(cv_summary).sort_values("MeanBalancedAcc", ascending=False)
pd.concat(fold_dfs).to_csv("NestedCV_folds_all.csv", index=False)
cv_df.to_csv("NestedCV_summary.csv", index=False)
pd.DataFrame(best_params).to_csv("NestedCV_best_params.csv")

print("\n Nested CV summary:\n", cv_df)
print("\n Selected params:\n", best_params)

# -------------------------
#  Final model on hold-out
# -------------------------
winner = cv_df.iloc[0]["Model"]
final_model = models[winner].set_params(**best_params[winner])
final_model.fit(X_train, y_train)

y_hat = final_model.predict(X_test)

# hold-out global metrics
holdout_metrics = {
    "Accuracy": accuracy_score(y_test, y_hat),
    "BalancedAcc": balanced_accuracy_score(y_test, y_hat),
    "F1_macro": f1_score(y_test, y_hat, average="macro"),
    "Kappa": cohen_kappa_score(y_test, y_hat)
}
pd.DataFrame([holdout_metrics]).to_csv("Holdout_metrics.csv", index=False)

# per-class report
report = classification_report(y_test, y_hat, output_dict=True, zero_division=0)
per_class = (pd.DataFrame(report).T
             .loc[[c for c in report.keys() if c in np.unique(y_test)]]
             .rename_axis("Class").reset_index())
per_class.to_csv("Holdout_per_class.csv", index=False)

# confusion matrices
cm = confusion_matrix(y_test, y_hat, labels=np.unique(y))
cm_df = pd.DataFrame(cm, index=np.unique(y), columns=np.unique(y))
cm_df.to_csv("Holdout_confusion_matrix.csv")

cm_norm = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis]
cm_norm_df = pd.DataFrame(cm_norm, index=np.unique(y), columns=np.unique(y))
cm_norm_df.to_csv("Holdout_confusion_matrix_normalized.csv")

print("Hold-out metrics:", holdout_metrics)
print("Per-class (hold-out):\n", per_class)
print("Confusion matrix (hold-out):\n", cm_df)

import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ---- Load results ----
cv_df = pd.read_csv("NestedCV_summary.csv")
holdout = pd.read_csv("Holdout_metrics.csv").iloc[0]
per_class = pd.read_csv("Holdout_per_class.csv")
cm = pd.read_csv("Holdout_confusion_matrix.csv", index_col=0)



# -------------------------
# A. Nested CV vs Hold-out
# -------------------------
plt.figure(figsize=(5,4))
ax = sns.barplot(data=cv_df, x="Model", y="MeanBalancedAcc",
                 palette="pastel", errorbar=None)

# Manual error bars
for i, (mean, std) in enumerate(zip(cv_df["MeanBalancedAcc"], cv_df["StdBalancedAcc"])):
    ax.errorbar(i, mean, yerr=std, color="black", capsize=4, fmt='none', lw=1.2)

plt.axhline(holdout["BalancedAcc"], color="red", linestyle="--")
plt.text(0.95, holdout["BalancedAcc"]+0.005, "Hold-out_Accuracy (RF)", ha="right", fontsize=10, style="italic")

plt.ylabel("Balanced Accuracy", fontsize=12)
plt.ylim(0.85, 1.01)
sns.despine()
plt.tight_layout()
plt.savefig("Figure_NestedCV_vs_Holdout.tiff", dpi=600)
plt.show()


# -------------------------
# B. Confusion Matrix (Counts)
# -------------------------
plt.figure(figsize=(6,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            cbar=False, square=True, annot_kws={"size":10})

plt.title("", fontsize=12, weight="bold")
plt.ylabel("True Class", fontsize=12)
plt.xlabel("Predicted Class", fontsize=12)
plt.tight_layout()
plt.savefig("Figure_ConfusionMatrix_Counts.tiff", dpi=600)
plt.show()