# -*- coding: utf-8 -*-
"""Scond_ML_PART2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpwqZK-Tq1Te6f3GAUDlwL1O4eYrIR9U

Feature importance and stability analysis
"""

# ===============================
#  Feature importance & Stability runs
# ===============================
import numpy as np, pandas as pd, time, os
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.inspection import permutation_importance

# ---------- Load & align ----------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)  # species x samples
meta = pd.read_csv("Merged_metadata_all.csv")
common = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common]
meta = meta[meta["Sample_ID"].isin(common)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]

X = tpm.T.values
y = meta["Group"].values
species = tpm.index
print(f"Features: {X.shape} | Labels: {np.unique(y)} counts: {pd.Series(y).value_counts().to_dict()}")

# ---------- Settings ----------
n_repeats     = 50      # stability repeats
top_k         = 60      # only top-K features for permutation
perm_repeats  = 3       # repeats inside permutation importance
save_every    = 5       # partial save cadence (repeats)

# Use your tuned params (from Nested CV)
rf_params = {"n_estimators": 500, "max_depth": None, "max_features": 0.5, "min_samples_leaf": 1}
dt_params = {"max_depth": 5, "min_samples_leaf": 3, "min_samples_split": 2}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

rf_importances, dt_importances, perm_importances = [], [], []

# Ensure output dir exists
os.makedirs("importance_partials", exist_ok=True)

for repeat in range(1, n_repeats + 1):
    for fold, (train_idx, test_idx) in enumerate(cv.split(X, y), 1):
        t0 = time.time()
        X_tr, X_te = X[train_idx], X[test_idx]
        y_tr, y_te = y[train_idx], y[test_idx]

        # ---- 1) Fit RF on ALL features; record its Gini importances ----
        rf_full = RandomForestClassifier(
            random_state=repeat, n_jobs=-1, class_weight="balanced", **rf_params
        )
        rf_full.fit(X_tr, y_tr)
        rf_importances.append(rf_full.feature_importances_)

        # ---- 2) Fit DT on ALL features; record its importances ----
        dt = DecisionTreeClassifier(
            random_state=repeat, class_weight="balanced", **dt_params
        )
        dt.fit(X_tr, y_tr)
        dt_importances.append(dt.feature_importances_)

        # ---- 3) Permutation importance on top-K features ONLY ----
        # pick top-K indices from the full-RF importances
        top_idx = np.argsort(rf_full.feature_importances_)[-top_k:]

        # REFIT a *new* RF on only those K columns
        X_tr_k = X_tr[:, top_idx]
        X_te_k = X_te[:, top_idx]

        rf_k = RandomForestClassifier(
            random_state=repeat, n_jobs=-1, class_weight="balanced", **rf_params
        )
        rf_k.fit(X_tr_k, y_tr)

        # Now permute those same K columns
        perm = permutation_importance(
            rf_k, X_te_k, y_te, n_repeats=perm_repeats, random_state=repeat, n_jobs=-1
        )

        # place the K importances back into a length-1104 vector
        perm_vec = np.zeros(X.shape[1])
        perm_vec[top_idx] = perm.importances_mean
        perm_importances.append(perm_vec)

        print(f"Repeat {repeat}/{n_repeats}, Fold {fold}/5 in {time.time()-t0:.1f}s")

    # ---- Partial save every `save_every` repeats ----
    if repeat % save_every == 0:
        pd.DataFrame(rf_importances, columns=species).to_csv(
            f"importance_partials/RF_importances_partial_{repeat}.csv", index=False
        )
        pd.DataFrame(dt_importances, columns=species).to_csv(
            f"importance_partials/DT_importances_partial_{repeat}.csv", index=False
        )
        pd.DataFrame(perm_importances, columns=species).to_csv(
            f"importance_partials/Permutation_importances_partial_{repeat}.csv", index=False
        )
        print(f"Partial save @ repeat {repeat}")
        # (Optional) also flush to Drive if mounted: from google.colab import drive; drive.flush_and_unmount()

# ---------- Final save ----------
pd.DataFrame(rf_importances, columns=species).to_csv("RF_importances_repeated.csv", index=False)
pd.DataFrame(dt_importances, columns=species).to_csv("DT_importances_repeated.csv", index=False)
pd.DataFrame(perm_importances, columns=species).to_csv("Permutation_importances_topK.csv", index=False)

print("Finished! All importances saved.")

# ===============================
# Consensus Feature Ranking
# ===============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ---- Load saved results ----
rf_df   = pd.read_csv("RF_importances_repeated.csv")     # shape: repeats × species
dt_df   = pd.read_csv("DT_importances_repeated.csv")
perm_df = pd.read_csv("Permutation_importances_topK.csv")

species = rf_df.columns

# ---- 1) Aggregate mean importance per species ----
rf_mean   = rf_df.mean().rename("RF")
dt_mean   = dt_df.mean().rename("DT")
perm_mean = perm_df.mean().rename("Permutation")

agg = pd.concat([rf_mean, dt_mean, perm_mean], axis=1)

# ---- 2) Normalize each method to [0,1] for comparability ----
agg_norm = agg.div(agg.max())

# ---- 3) Rank within each method (1 = most important) ----
ranks = agg.rank(ascending=False)
agg["RF_rank"]   = ranks["RF"]
agg["DT_rank"]   = ranks["DT"]
agg["Perm_rank"] = ranks["Permutation"]

# ---- 4) Consensus rank = mean of ranks ----
agg["Consensus_rank"] = agg[["RF_rank","DT_rank","Perm_rank"]].mean(axis=1)

# ---- 5) Final sorted table ----
consensus = agg.sort_values("Consensus_rank").reset_index().rename(columns={"index":"Species"})
consensus.to_csv("Consensus_Feature_Ranking.csv", index=False)

print("onsensus ranking saved! Top 10 species:")
print(consensus.head(10))

import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------------
# A. Consensus Rank Barplot (Top 30)
# ------------------------------
topN = 30
consensus_sorted = consensus.head(topN)

plt.figure(figsize=(7,8))
palette = ["#1f77b4" if i>=5 else "#d62728" for i in range(topN)]  # red highlight for top 5
sns.barplot(
    data=consensus_sorted,
    y="Species", x="Consensus_rank",
    palette=palette, edgecolor="black"
)
plt.gca().invert_yaxis()

plt.xlabel("Consensus Rank (lower = more important)", fontsize=12, weight="bold")
plt.ylabel("")
plt.title("", fontsize=14, weight="bold")

sns.despine()
plt.grid(axis="x", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig("Consensus_Top30_Barplot.tiff", dpi=600, bbox_inches="tight")
plt.show()

# ------------------------------
# B. Boxplot of Importance Stability (Top 15 species)
# ------------------------------
top_species = consensus["Species"].head(15)

plt.figure(figsize=(9,5))
ordered = rf_df[top_species].melt(var_name="Species", value_name="Importance")
# Order by median importance
order = ordered.groupby("Species")["Importance"].median().sort_values(ascending=False).index

sns.boxplot(
    data=ordered, x="Species", y="Importance",
    order=order,
    palette="Set2",  # clean palette
    width=0.6,
    showcaps=True,
    boxprops={"edgecolor":"black"},
    whiskerprops={"color":"black"},
    medianprops={"color":"black", "linewidth":2}
)

plt.xticks(rotation=45, ha="right", fontsize=10)
plt.ylabel("Feature Importance (RF Gini)", fontsize=12, weight="bold")
plt.xlabel("")
plt.title("", fontsize=14, weight="bold")

sns.despine()
plt.grid(axis="y", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig("RF_ImportanceStability_Top15.tiff", dpi=600, bbox_inches="tight")
plt.show()

# ===============================
# Per-Environment Feature Importance
# ===============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ---- Load saved results ----
rf_df   = pd.read_csv("RF_importances_repeated.csv")     # repeats × species
dt_df   = pd.read_csv("DT_importances_repeated.csv")
perm_df = pd.read_csv("Permutation_importances_topK.csv")

species = rf_df.columns

# ---- Load metadata (for labels) ----
meta = pd.read_csv("Merged_metadata_all.csv")
y = meta["Group"].values

# ---- Load TPM for alignment ----
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)
common_samples = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common_samples]
meta = meta[meta["Sample_ID"].isin(common_samples)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]   # enforce same order

X = tpm.T.values

# ---- 1) Train RF per environment (one-vs-rest) ----
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold

rf_params = {"n_estimators": 500, "max_depth": None, "max_features": 0.5, "min_samples_leaf": 1}
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

env_importances = {env: [] for env in np.unique(y)}

for env in np.unique(y):
    # binary labels: env vs rest
    y_bin = (y == env).astype(int)

    for tr_idx, te_idx in cv.split(X, y_bin):
        X_tr, X_te = X[tr_idx], X[te_idx]
        y_tr, y_te = y_bin[tr_idx], y_bin[te_idx]

        rf = RandomForestClassifier(
            random_state=42, n_jobs=-1, class_weight="balanced", **rf_params
        )
        rf.fit(X_tr, y_tr)
        env_importances[env].append(rf.feature_importances_)

# ---- 2) Aggregate mean importances per environment ----
env_mean = {
    env: np.mean(importances, axis=0) for env, importances in env_importances.items()
}
env_df = pd.DataFrame(env_mean, index=species)

# ---- 3) For each environment, rank top features ----
topN = 20
for env in env_df.columns:
    top_features = env_df[env].sort_values(ascending=False).head(topN)
    top_features.to_csv(f"TopFeatures_{env}.csv")

    plt.figure(figsize=(6,6))
    sns.barplot(
        x=top_features.values, y=top_features.index,
        color="steelblue"
    )
    plt.xlabel("Mean RF Importance")
    plt.ylabel("")
    plt.title("")
    plt.tight_layout()
    plt.savefig(f"TopFeatures_{env}_Barplot.tiff", dpi=600)
    plt.close()

print("Per-environment top features saved")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from matplotlib.patches import Rectangle

# ---- Load abundance and metadata ----
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)  # species x samples
meta = pd.read_csv("Merged_metadata_all.csv")

# Align samples
common = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common]
meta = meta[meta["Sample_ID"].isin(common)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]

# ---- Load feature importance ----
rf_df = pd.read_csv("RF_importances_repeated.csv")  # rows = repeats, cols = species
mean_importance = rf_df.mean().sort_values(ascending=False)

# Select top 50 species
top_species = mean_importance.head(50).index
tpm_top = tpm.loc[top_species]

# ---- Collapse to environments ----
tpm_top_T = tpm_top.T
tpm_top_T["Group"] = meta["Group"].values
env_means = tpm_top_T.groupby("Group").mean().T

# ---- Normalize across rows (z-score per species) ----
scaler = StandardScaler()
env_means_scaled = pd.DataFrame(
    scaler.fit_transform(env_means),
    index=env_means.index,
    columns=env_means.columns
)

# ---- Order environments manually (optional) ----
env_order = ["Hosp_env", "Hosp_sewage", "Ambulance", "Public_transp"]
env_means_scaled = env_means_scaled[env_order]

# ---- Plot heatmap ----
plt.figure(figsize=(9,12))
ax = sns.heatmap(env_means_scaled,
                 cmap="RdBu_r", center=0,
                 linewidths=0.2, linecolor="lightgrey",
                 cbar_kws={"label": "Z-score (Normalized Abundance)"},
                 yticklabels=True)

# ---- Improve labels ----
plt.title("", fontsize=16, weight="bold", pad=20)
plt.xlabel("Environment", fontsize=13, weight="bold")
plt.ylabel("Species", fontsize=13, weight="bold")

# Bold highlight for top 10
for i, label in enumerate(ax.get_yticklabels()):
    if i < 10:  # top 10
        label.set_weight("bold")
        label.set_color("black")
    label.set_fontsize(9)

# Increase x-axis font size
for label in ax.get_xticklabels():
    label.set_fontsize(11)
    label.set_weight("bold")

# Add alternating shading for readability
for i in range(len(env_means_scaled)):
    if i % 2 == 0:
        ax.add_patch(Rectangle((-0.5, i-0.5), len(env_order), 1,
                               fill=False, edgecolor="grey", lw=0.3))

plt.tight_layout()
plt.savefig("TopSpecies_EnvHeatmap.tiff", dpi=600, bbox_inches="tight")
plt.show()