# -*- coding: utf-8 -*-
"""Last_ML_PART3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGBiaDZhuOGjs5d3liKJNn1L1ZgRf1kE

**Simulations Pipeline For Biosurveillance (Donor-Recipient Framework)**
"""

# ===============================
# Synthetic Mixing Simulations and Minimal Detectable Contamination (MDC) Analysis -Dose–Response Framework
# ===============================

import numpy as np, pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

# -------------------------
# 0) Load & align
# -------------------------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)  # species x samples
meta = pd.read_csv("Merged_metadata_all.csv")

common = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common]
meta = meta[meta["Sample_ID"].isin(common)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]

X = tpm.T.values                   # samples x species
y = meta["Group"].values           # environment labels
classes = meta["Group"].unique()
print("✔ Data:", X.shape, "classes:", dict(pd.Series(y).value_counts()))

# -------------------------
# 1) Train/hold-out split & final model
# -------------------------
X_tr, X_te, y_tr, y_te = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Tuned params from nested CV
rf_params = {"n_estimators": 500, "max_depth": None, "max_features": 0.5, "min_samples_leaf": 1}
dt_params = {"max_depth": 5, "min_samples_leaf": 3, "min_samples_split": 2}

rf = RandomForestClassifier(random_state=42, n_jobs=-1, class_weight="balanced", **rf_params)
rf.fit(X_tr, y_tr)

dt = DecisionTreeClassifier(random_state=42, class_weight="balanced", **dt_params)
dt.fit(X_tr, y_tr)

model = rf         # <— using RF
model_name = "RandomForest"

# -------------------------
# 2) Helpers
# -------------------------
from math import sqrt

def wilson_ci(k, n, z=1.96):
    if n == 0: return (0.0, 0.0)
    p = k / n
    denom = 1 + z**2/n
    center = (p + z**2/(2*n)) / denom
    half = z * sqrt(p*(1-p)/n + z**2/(4*n**2)) / denom
    return max(0, center - half), min(1, center + half)

def mix_samples(x_rec, x_don, alpha):
    return (1.0 - alpha) * x_rec + alpha * x_don

def mix_centroids(mu_rec, mu_don, alpha):
    return (1.0 - alpha) * mu_rec + alpha * mu_don

def refine_alphas(coarse_alphas, a_hit, step=0.01):
    if np.isnan(a_hit): return coarse_alphas
    lo = max(0.0, a_hit - 0.05)
    hi = min(1.0, a_hit + 0.05)
    fine = np.arange(lo, hi + 1e-9, step)
    return np.unique(np.concatenate([coarse_alphas, fine]))

# Precompute centroids
by_env = {g: X[meta["Group"]==g] for g in classes}
centroids = {g: by_env[g].mean(axis=0) for g in classes}
env_list = list(by_env.keys())

# -------------------------
# 3) Simulation grid
# -------------------------
alphas = np.linspace(0, 1.0, 21)   # coarse grid (0.05 step)
n_pairs = 50                       # replicates per alpha
prob_thresh = 0.8

rng = np.random.default_rng(123)

records = []

for rec in env_list:
    for don in env_list:
        if rec == don: continue
        X_rec, X_don = by_env[rec], by_env[don]
        mu_r, mu_d   = centroids[rec], centroids[don]

        # ---- coarse pass (sample mode only) ----
        coarse_rows = []
        for a in alphas:
            cnt = 0
            for _ in range(n_pairs):
                x_r = X_rec[rng.integers(0, X_rec.shape[0])]
                x_d = X_don[rng.integers(0, X_don.shape[0])]
                x_mix = mix_samples(x_r, x_d, a).reshape(1, -1)
                cnt += (model.predict(x_mix)[0] == don)
            p = cnt / n_pairs
            lo, hi = wilson_ci(cnt, n_pairs)
            coarse_rows.append({"Mode":"sample","Recipient":rec,"Donor":don,"alpha":a,
                                "P_donor":p,"CI_low":lo,"CI_high":hi})
        coarse_df = pd.DataFrame(coarse_rows)
        hit = coarse_df[coarse_df["P_donor"] >= prob_thresh]
        a_hit = hit["alpha"].iloc[0] if len(hit) else np.nan
        # refine if needed
        a_refined = refine_alphas(alphas, a_hit, step=0.01)

        # ---- rerun with refined grid ----
        for a in a_refined:
            cnt = 0
            for _ in range(n_pairs):
                x_r = X_rec[rng.integers(0, X_rec.shape[0])]
                x_d = X_don[rng.integers(0, X_don.shape[0])]
                x_mix = mix_samples(x_r, x_d, a).reshape(1, -1)
                cnt += (model.predict(x_mix)[0] == don)
            p = cnt / n_pairs
            lo, hi = wilson_ci(cnt, n_pairs)
            records.append({"Mode":"sample","Recipient":rec,"Donor":don,"alpha":a,
                            "P_donor":p,"CI_low":lo,"CI_high":hi})

        # ---- centroid mode ----
        for a in a_refined:
            x_mix = mix_centroids(mu_r, mu_d, a).reshape(1, -1)
            y_hat = model.predict(x_mix)[0]
            p = float(y_hat == don)
            records.append({"Mode":"centroid","Recipient":rec,"Donor":don,"alpha":a,
                            "P_donor":p,"CI_low":p,"CI_high":p})

# -------------------------
# 4) Save dose–response
# -------------------------
sim_df = pd.DataFrame(records)
sim_df.to_csv("Simulations_donor_recipient_withCI.csv", index=False)
print("✔ Saved: Simulations_donor_recipient_withCI.csv")

# -------------------------
# 5) Minimal Detectable Contamination (MDC)
# -------------------------
def min_detectable_alpha(sub, thresh=0.8):
    tmp = sub.sort_values("alpha")
    hit = tmp[tmp["P_donor"] >= thresh]
    return hit["alpha"].iloc[0] if len(hit) else np.nan

mdc_rows = []
for mode in ["sample","centroid"]:
    for rec in env_list:
        for don in env_list:
            if rec == don: continue
            sub = sim_df[(sim_df["Mode"]==mode)&(sim_df["Recipient"]==rec)&(sim_df["Donor"]==don)]
            mdc_rows.append({"Mode":mode,"Recipient":rec,"Donor":don,
                             "MDC":min_detectable_alpha(sub, prob_thresh)})
mdc_df = pd.DataFrame(mdc_rows)
mdc_df.to_csv("Simulations_MDC_table_refined.csv", index=False)
print("✔ Saved: Simulations_MDC_table_refined.csv")

# ===============================
# Plotting: Dose–Response + MDC Heatmaps
# ===============================
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Load simulation results
sim_df = pd.read_csv("Simulations_dose_response_withCI.csv")
mdc_df = pd.read_csv("Simulations_MDC_table_refined.csv")

# Custom environment colors (consistent with R)
env_colors = {
    "Ambulance": "#1f77b4",
    "Hosp_env": "#aec7e8",
    "Hosp_sewage": "#ff7f0e",
    "Public_transp": "#fdbf6f"
}

# -------------------------
# A. Dose–response curves (per recipient)
# -------------------------
for rec in sim_df["Recipient"].unique():
    fig, ax = plt.subplots(figsize=(6,4)) # Create figure and axes

    # Subset for this recipient
    for don in sim_df["Donor"].unique():
        if rec == don:
            continue
        sub = sim_df[(sim_df["Recipient"]==rec) & (sim_df["Donor"]==don) & (sim_df["Mode"]=="sample")]

        if len(sub)==0:
            continue

        # Plot mean curve
        ax.plot(sub["alpha"], sub["P_donor"],
                 label=f"{don} (sample)",
                 color=env_colors.get(don,"black"),
                 lw=2)

        # Add CI ribbon
        ax.fill_between(sub["alpha"], sub["CI_low"], sub["CI_high"],
                         color=env_colors.get(don,"black"), alpha=0.2)

        # Centroid line
        sub_c = sim_df[(sim_df["Recipient"]==rec) & (sim_df["Donor"]==don) & (sim_df["Mode"]=="centroid")]
        if len(sub_c)>0:
            ax.plot(sub_c["alpha"], sub_c["P_donor"],
                     linestyle="--", lw=1.5, color=env_colors.get(don,"black"),
                     label=f"{don} (centroid)")

    ax.axhline(0.8, linestyle=":", color="gray", lw=1)
    ax.set_ylim(-0.02,1.02)
    ax.set_xlabel("Contamination fraction (α)", fontsize=10)
    ax.set_ylabel("P(predicted donor)", fontsize=10)
    ax.set_title(f"(Recipient = {rec})", fontsize=10, weight="bold")
    ax.legend(frameon=False, fontsize=9, bbox_to_anchor=(1.05,1), loc="upper left")
    sns.despine(ax=ax)

    # Increase border thickness
    for spine in ax.spines.values():
        spine.set_linewidth(2) # Adjust the thickness as needed

    plt.tight_layout()
    plt.savefig(f"Figure_Sim_DonorRecipient_{rec}.tiff", dpi=600)
    plt.show()

print("✔ Saved individual donor–recipient figures per recipient")

# -------------------------
# B. MDC heatmaps
# -------------------------
# Sample mode
hm_sample = mdc_df[mdc_df["Mode"]=="sample"].pivot(index="Recipient", columns="Donor", values="MDC")
plt.figure(figsize=(5.5,4.5))
sns.heatmap(hm_sample, annot=True, fmt=".2f", cmap="Reds",
            cbar_kws={"label":"Minimal α to flip (≥80%)"})
plt.title("", fontsize=14, weight="bold")
plt.xlabel("Donor", fontsize=10)
plt.ylabel("Recipient", fontsize=10 )
sns.despine()
plt.tight_layout()
plt.savefig("Figure_Sim_MDC_heatmap_sample.tiff", dpi=600)
plt.show()

# Centroid mode
hm_centroid = mdc_df[mdc_df["Mode"]=="centroid"].pivot(index="Recipient", columns="Donor", values="MDC")
plt.figure(figsize=(5.5,4.5))
sns.heatmap(hm_centroid, annot=True, fmt=".2f", cmap="Reds",
            cbar_kws={"label":"Minimal α to flip (≥80%)"})
plt.title("", fontsize=14, weight="bold")
plt.xlabel("Donor", fontsize=10)
plt.ylabel("Recipient", fontsize=10)
sns.despine()
plt.tight_layout()
plt.savefig("Figure_Sim_MDC_heatmap_centroid.tiff", dpi=600)
plt.show()

print("✔ Saved MDC heatmaps (sample + centroid)")

"""**Simulations Pipeline For Biosurveillance (Entropy-Based)- Ecological Stability framework**"""

# ===============================
# Part A: Synthetic Blending Simulation
# ===============================

import pandas as pd, numpy as np, itertools
import matplotlib.pyplot as plt, seaborn as sns
from scipy.stats import entropy
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

# -------------------------
# Load data
# -------------------------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)
meta = pd.read_csv("Merged_metadata_all.csv")

# Align sample IDs
common = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common]
meta = meta[meta["Sample_ID"].isin(common)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]

# Features + labels
X = tpm.T.values
y = meta["Group"].values
species_cols = tpm.index.tolist()

le = LabelEncoder()
y_enc = le.fit_transform(y)

# -------------------------
# Use tuned RF parameters
# -------------------------
rf_params = {
    "n_estimators": 500,
    "max_depth": None,
    "max_features": 0.5,
    "min_samples_leaf": 1,
    "random_state": 42,
    "n_jobs": -1,
    "class_weight": "balanced"
}

print("Using tuned RF params:", rf_params)

# Train RF with tuned params
rf = RandomForestClassifier(**rf_params)
rf.fit(X, y_enc)

# Build pivot table for blending
pivot_df = pd.DataFrame(X, columns=species_cols)
pivot_df["Sample_ID"] = meta["Sample_ID"]
pivot_df["Group"] = meta["Group"]

# -------------------------
# Synthetic mixing simulation
# -------------------------
env_names = pivot_df["Group"].unique()
grouped = pivot_df.groupby("Group")

blend_ratios = np.linspace(0, 1, 11)  # 0–100% in steps of 10%
results = []

for env_a, env_b in itertools.combinations(env_names, 2):
    print(f"Simulating: {env_a} ↔ {env_b}")
    samples_a = grouped.get_group(env_a)[species_cols].values
    samples_b = grouped.get_group(env_b)[species_cols].values
    n_samples = min(len(samples_a), len(samples_b))

    for ratio in blend_ratios:
        for i in range(n_samples):
            blend = ratio * samples_a[i] + (1-ratio) * samples_b[i]
            proba = rf.predict_proba([blend])[0]
            pred_class = np.argmax(proba)
            pred_label = le.inverse_transform([pred_class])[0]
            conf = np.max(proba)
            ent = entropy(proba, base=2)

            results.append({
                "Env_A": env_a, "Env_B": env_b,
                "Blend_A": ratio, "Blend_B": 1-ratio,
                "Predicted": pred_label,
                "Confidence": conf, "Entropy": ent
            })

# Save blend-level results
blend_df = pd.DataFrame(results)
blend_df.to_csv("synthetic_blend_entropy.csv", index=False)

# -------------------------
# Extract switch points
# -------------------------
switch_points = []
for (env_a, env_b), group in blend_df.groupby(["Env_A","Env_B"]):
    group = group.sort_values("Blend_A")
    preds = group["Predicted"].values
    blends = group["Blend_A"].values

    for i in range(1, len(preds)):
        if preds[i] != preds[i-1]:
            switch_points.append({
                "Env_A": env_a, "Env_B": env_b,
                "Switch_From": preds[i-1], "Switch_To": preds[i],
                "Blend_Percent_A": blends[i], "Blend_Percent_B": 1-blends[i]
            })
            break

switch_df = pd.DataFrame(switch_points)
switch_df.to_csv("synthetic_transition_points.csv", index=False)

print("Finished Part A: Generated synthetic_blend_entropy.csv and synthetic_transition_points.csv")

# ===============================
# Synthetic Mixing Curves
# ===============================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load results
blend_df = pd.read_csv("synthetic_blend_entropy.csv")

# Environment color palette (same as before)
env_colors = {
    "Ambulance": "#1f77b4",
    "Hosp_env": "#aec7e8",
    "Hosp_sewage": "#ff7f0e",
    "Public_transp": "#fdbf6f"
}

# Loop through each recipient–donor pair
for (env_a, env_b), subset in blend_df.groupby(["Env_A", "Env_B"]):
    fig, ax = plt.subplots(figsize=(5,4)) # Create figure and axes

    # Confidence curves
    sns.lineplot(
        data=subset, x="Blend_A", y="Confidence", hue="Predicted",
        palette=env_colors, marker="o", linewidth=3, alpha=0.9, ax=ax # Pass ax to lineplot
    )

    # Add vertical line at 50/50 mixing
    ax.axvline(0.5, linestyle="--", color="gray", lw=2, alpha=0.7)

    # Titles and labels
    ax.set_title(f"{env_a} ↔ {env_b}", fontsize=13, weight="bold")
    ax.set_xlabel(f"% {env_a}", fontsize=11)
    ax.set_ylabel("Prediction Confidence", fontsize=11)
    ax.set_ylim(0, 1.05)

    # Legend styling
    ax.legend(loc='lower left', fontsize=9, frameon=False)
    sns.despine(ax=ax) # Pass ax to despine

    # Increase border thickness
    for spine in ax.spines.values():
        spine.set_linewidth(1.5) # Adjust the thickness as needed

    plt.tight_layout()

    # Save separately
    fname = f"SyntheticMixingCurve_{env_a}_vs_{env_b}.tiff".replace(" ","_")
    plt.savefig(fname, dpi=600, bbox_inches="tight")
    plt.show()

print("✔ Separate synthetic mixing confidence curves saved for each environment pair.")

# ===============================
# Entropy Curves
# ===============================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load simulation results
blend_df = pd.read_csv("synthetic_blend_entropy.csv")
switch_df = pd.read_csv("synthetic_transition_points.csv")

# Max entropy reference (depends on number of classes)
max_entropy = np.log2(blend_df["Predicted"].nunique())

# Colors for environments
env_colors = {
    "Ambulance": "#1f77b4",
    "Hosp_env": "#aec7e8",
    "Hosp_sewage": "#ff7f0e",
    "Public_transp": "#fdbf6f"
}

# Loop through each recipient-donor pair
for (env_a, env_b), subset in blend_df.groupby(["Env_A", "Env_B"]):
    fig, ax = plt.subplots(figsize=(5,4)) # Create figure and axes

    # Mean ± SD across replicates
    summary = subset.groupby("Blend_A")["Entropy"].agg(["mean","std"]).reset_index()
    sns.lineplot(x="Blend_A", y="mean", data=summary,
                 color=env_colors.get(env_a, "steelblue"),
                 marker="o", linewidth=2, ax=ax) # Pass ax to lineplot
    ax.fill_between(summary["Blend_A"], summary["mean"]-summary["std"],
                     summary["mean"]+summary["std"], alpha=0.25,
                     color=env_colors.get(env_a, "steelblue"))

    # Mark theoretical maximum entropy
    ax.axhline(max_entropy, linestyle="--", color="red", linewidth=2)

    # Mark switch point (if available)
    sw = switch_df[(switch_df["Env_A"]==env_a) & (switch_df["Env_B"]==env_b)]
    if not sw.empty:
        ax.axvline(sw.iloc[0]["Blend_Percent_A"], linestyle="--",
                    color="black", linewidth=2)

    # Aesthetics
    ax.set_title(f"{env_a} ↔ {env_b}", fontsize=13, weight="bold")
    ax.set_xlabel(f"% {env_a}", fontsize=11)
    ax.set_ylabel("Entropy (Uncertainty)", fontsize=11)
    ax.set_ylim(0, max_entropy+0.2)
    sns.despine(ax=ax) # Pass ax to despine

    # Increase border thickness
    for spine in ax.spines.values():
        spine.set_linewidth(1.5) # Adjust the thickness as needed


    plt.tight_layout()

    # Save separately
    fname = f"EntropyCurve_{env_a}_vs_{env_b}.tiff".replace(" ","_")
    plt.savefig(fname, dpi=600, bbox_inches="tight")
    plt.show()

print("✔ Separate entropy curves saved for each environment pair.")

# ===============================
# Switch Point Heatmap
# ===============================
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load transition points
switch_df = pd.read_csv("synthetic_transition_points.csv")

# Build symmetric matrix of switch blend ratios
envs = sorted(set(switch_df["Env_A"]) | set(switch_df["Env_B"]))
matrix = pd.DataFrame(index=envs, columns=envs, dtype=float)

for _, row in switch_df.iterrows():
    a, b = row["Env_A"], row["Env_B"]
    matrix.loc[a, b] = row["Blend_Percent_A"]
    matrix.loc[b, a] = row["Blend_Percent_B"]

# Plot
plt.figure(figsize=(8,7))
sns.set_theme(style="whitegrid", context="talk")

ax = sns.heatmap(
    matrix.astype(float),
    annot=True, fmt=".2f", cmap="RdBu_r",
    linewidths=0.7, linecolor="white",
    cbar_kws={"label": "Blend Ratio (α at switch)"}
)

plt.title("Switch Point", fontsize=15, weight="bold")
plt.xlabel("To Environment", fontsize=12, weight="bold")
plt.ylabel("From Environment", fontsize=12, weight="bold")

# Borders
for _, spine in ax.spines.items():
    spine.set_visible(True)
    spine.set_linewidth(1.5)
    spine.set_color("black")

plt.tight_layout()
plt.savefig("SwitchPoint_Heatmap.tiff", dpi=600, bbox_inches="tight")
plt.show()

# ===============================
# Dominance Matrix
# ===============================
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Build dominance matrix
dominance_matrix = pd.DataFrame(0, index=envs, columns=envs)

for _, row in switch_df.iterrows():
    winner, loser = row["Switch_To"], row["Switch_From"]
    dominance_matrix.loc[winner, loser] += 1

# Plot
plt.figure(figsize=(8,7))
sns.set_theme(style="whitegrid", context="talk")

ax = sns.heatmap(
    dominance_matrix, annot=True, fmt="d", cmap="YlGnBu",
    linewidths=0.7, linecolor="white",
    cbar_kws={"label": "Number of Wins"}
)

plt.title("Environment Dominance Matrix", fontsize=15, weight="bold")
plt.xlabel("Loser", fontsize=12, weight="bold")
plt.ylabel("Winner", fontsize=12, weight="bold")

# Borders
for _, spine in ax.spines.items():
    spine.set_visible(True)
    spine.set_linewidth(1.5)
    spine.set_color("black")

plt.tight_layout()
plt.savefig("Environment_Dominance_Matrix.tiff", dpi=600, bbox_inches="tight")
plt.show()

# ===============================
# Contamination Risk Scoring + Sensitivity Analysis
# ===============================

import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from sklearn.decomposition import PCA
from scipy.stats import spearmanr

# -------------------------
# Step 1. Load core inputs
# -------------------------
switch_df = pd.read_csv("synthetic_transition_points.csv")
blend_df  = pd.read_csv("synthetic_blend_entropy.csv")
pivot_df  = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0).T
pivot_df["Group"] = pd.read_csv("Merged_metadata_all.csv").set_index("Sample_ID").loc[pivot_df.index, "Group"]
species_cols = pivot_df.columns.drop("Group")

# -------------------------
# Step 2. Compute risk metrics
# -------------------------
# (i) Overridden counts
loser_counts = switch_df["Switch_From"].value_counts()
loser_counts.name = "Times_Overridden"

# (ii) Entropy
env_entropy = {}
for env in blend_df["Env_A"].unique():
    mask = (blend_df["Env_A"] == env) | (blend_df["Env_B"] == env)
    env_entropy[env] = blend_df[mask].groupby("Blend_A")["Entropy"].mean().mean()
entropy_df = pd.DataFrame.from_dict(env_entropy, orient="index", columns=["Mean_Entropy"])

# (iii) Richness + variance
richness_dict, variance_dict = {}, {}
for env in pivot_df["Group"].unique():
    samples = pivot_df[pivot_df["Group"] == env][species_cols]
    richness_dict[env] = (samples > 0).sum(axis=1).mean()
    variance_dict[env] = samples.var(axis=1).mean()

richness_df = pd.DataFrame.from_dict(richness_dict, orient="index", columns=["Richness"])
variance_df = pd.DataFrame.from_dict(variance_dict, orient="index", columns=["Variance"])

# Merge all
risk_df = pd.concat([loser_counts, entropy_df, richness_df, variance_df], axis=1).fillna(0)

# Normalize
for col in ["Times_Overridden", "Mean_Entropy", "Richness", "Variance"]:
    risk_df[f"Norm_{col}"] = (risk_df[col] - risk_df[col].min()) / (risk_df[col].max() - risk_df[col].min())

# -------------------------
# Step 3. Three scoring schemes
# -------------------------
# A) Primary weights
risk_df["Risk_Primary"] = (
    0.4 * risk_df["Norm_Times_Overridden"] +
    0.3 * risk_df["Norm_Mean_Entropy"] +
    0.15 * risk_df["Norm_Richness"] +
    0.15 * risk_df["Norm_Variance"]
)

# B) Equal weights
risk_df["Risk_Equal"] = risk_df[
    ["Norm_Times_Overridden","Norm_Mean_Entropy","Norm_Richness","Norm_Variance"]
].mean(axis=1)

# C) PCA weights (PC1 loadings scaled positive)
X = risk_df[["Norm_Times_Overridden","Norm_Mean_Entropy","Norm_Richness","Norm_Variance"]].values
pca = PCA(n_components=1).fit(X)
weights = np.abs(pca.components_[0]) / np.sum(np.abs(pca.components_[0]))
risk_df["Risk_PCA"] = (X @ weights)

# -------------------------
# Step 4. Rank comparison
# -------------------------
rankings = risk_df[["Risk_Primary","Risk_Equal","Risk_PCA"]].rank(ascending=False)
correlations = pd.DataFrame(index=rankings.columns, columns=rankings.columns)

for i in rankings.columns:
    for j in rankings.columns:
        rho, _ = spearmanr(rankings[i], rankings[j])
        correlations.loc[i,j] = round(rho,3)

# Save
risk_df.to_csv("environment_risk_scores_all.csv")
correlations.to_csv("risk_score_rank_correlations.csv")

print("Risk scores computed + saved.")
print("\nRank correlations between schemes:\n", correlations)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd # Import pandas to use melt

# Assuming df_risk_long is your tidy dataframe in long format:
# Columns: ["Environment","Scheme","Risk_Score"]

# Create df_risk_long from risk_df
df_risk_long = risk_df.reset_index().melt(
    id_vars="index",
    value_vars=["Risk_Primary", "Risk_Equal", "Risk_PCA"],
    var_name="Scheme",
    value_name="Risk_Score"
)
df_risk_long = df_risk_long.rename(columns={"index": "Environment"}) # Rename the index column

plt.figure(figsize=(7,4))
sns.set_theme(style="whitegrid", context="talk")

ax = sns.barplot(
    data=df_risk_long,
    x="Risk_Score", y="Environment",
    hue="Scheme", palette=["#E76F51","#2A9D8F","#264653"],
    edgecolor="black"
)

# Add thick border
for spine in ax.spines.values():
    spine.set_visible(True) # Make sure all spines are visible
    spine.set_linewidth(1.5) # Adjust the thickness as needed
    spine.set_edgecolor('black') # Set border color

# Remove grid
ax.grid(False)


# Labels and title
ax.set_xlabel("Risk Score", fontsize=10, weight="bold")
ax.set_ylabel("Environment", fontsize=10, weight="bold")
ax.set_title("", fontsize=10, weight="bold")

# Legend below the plot, horizontal
ax.legend(
    title="", # Changed legend title
    loc='upper center', bbox_to_anchor=(0.5, -0.4), # Positioned below the plot
    fancybox=True, shadow=True, ncol=3, # Arranged horizontally
    frameon=False, fontsize=11
)

# Removed sns.despine()

plt.tight_layout()
plt.savefig("Contamination_Risk_Barplot.tiff", dpi=600, bbox_inches="tight")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd # Import pandas

# radar_df already prepared with columns: ["Environment","Overridden","Entropy","Richness","Variance"]
# Create radar_df from the existing risk_df DataFrame
radar_df = risk_df.reset_index().rename(columns={'index': 'Environment'})
radar_df = radar_df[['Environment', 'Norm_Times_Overridden', 'Norm_Mean_Entropy', 'Norm_Richness', 'Norm_Variance']]
radar_df = radar_df.rename(columns={
    'Norm_Times_Overridden': 'Overridden',
    'Norm_Mean_Entropy': 'Entropy',
    'Norm_Richness': 'Richness',
    'Norm_Variance': 'Variance'
})


categories = ["Overridden","Entropy","Richness","Variance"]
N = len(categories)
angles = np.linspace(0, 2*np.pi, N, endpoint=False).tolist()
angles += angles[:1]  # close loop

plt.figure(figsize=(8,6))
ax = plt.subplot(111, polar=True)

colors = ['#E76F51','#2A9D8F','#264653','#F4A261']

for i, row in radar_df.iterrows():
    values = row[categories].tolist()
    values += values[:1]
    ax.plot(angles, values, linewidth=2, label=row["Environment"], color=colors[i % len(colors)])
    ax.fill(angles, values, alpha=0.25, color=colors[i % len(colors)])

# Axes setup
ax.set_xticks(angles[:-1])
ax.set_xticklabels(categories, fontsize=11, weight="bold")
ax.set_ylim(0,1)
ax.set_yticks([0.2,0.4,0.6,0.8,1.0])
ax.set_yticklabels(["0.2","0.4","0.6","0.8","1.0"], fontsize=9)
ax.yaxis.grid(True, linestyle="dotted")

# Legend below the plot, horizontal
plt.legend(
    loc='upper center', bbox_to_anchor=(0.5, -0.08), fancybox=True, shadow=True, ncol=len(radar_df), # Positioned below and horizontal
    frameon=False, fontsize=11
)
plt.title("", fontsize=14, weight="bold", pad=20)

plt.tight_layout()
plt.savefig("Ecological_Risk_Radar_Clean.tiff", dpi=600, bbox_inches="tight")
plt.show()