# -*- coding: utf-8 -*-
"""Simulation_blending_ISME_Perspectives.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5FPCIbe-V_J9hKf3_B2LJMpXmlso20b
"""

# ===========================================================
# SYNTHETIC BLENDING AND ECOLOGICAL DOMINANCE (COUNTRY-LEVEL)
# ===========================================================

import pandas as pd, numpy as np, itertools
from sklearn.ensemble import RandomForestClassifier
from scipy.stats import entropy
import matplotlib.pyplot as plt, seaborn as sns

# -------------------------
# 0) Load data
# -------------------------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)
meta = pd.read_csv("Merged_metadata.csv")

# Align data
common = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common]
meta = meta[meta["Sample_ID"].isin(common)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]

# Features and labels
X = tpm.T.values
y = meta["Group"].values  # Original environment labels (RF model trained on this)

# -------------------------
# 1) Load or train Random Forest model (trained on environments)
# -------------------------
rf_params = {
    "n_estimators": 500,
    "max_depth": None,
    "max_features": 0.5,
    "min_samples_leaf": 1,
    "random_state": 42,
    "n_jobs": -1,
    "class_weight": "balanced"
}

rf = RandomForestClassifier(**rf_params)
rf.fit(X, y)
print(f"✔ RandomForest trained — hold-out accuracy approx: {rf.score(X, y):.3f}")

# -------------------------
# 2) Prepare data grouped by COUNTRY
# -------------------------
pivot_df = pd.DataFrame(X, columns=tpm.index)
pivot_df["Sample_ID"] = meta["Sample_ID"].values
pivot_df["Country"] = meta["Country"].values
pivot_df["Continent"] = meta["Continent"].values
pivot_df["Group"] = meta["Group"].values  # For reference

# Filter to representative countries (edit as needed)
selected_countries = [
    "USA", "China", "Singapore", "Finland",
    "Benin", "Burkina Faso", "South Africa"
]
pivot_df = pivot_df[pivot_df["Country"].isin(selected_countries)]

# -------------------------
# 3) Synthetic mixing simulations (Country–Country)
# -------------------------
blend_ratios = np.linspace(0, 1, 11)  # 0–100% blending
countries = pivot_df["Country"].unique()
species_cols = tpm.index.tolist()

results = []

for cA, cB in itertools.combinations(countries, 2):
    print(f"🌍 Simulating: {cA} ↔ {cB}")
    samples_A = pivot_df[pivot_df["Country"] == cA][species_cols].values
    samples_B = pivot_df[pivot_df["Country"] == cB][species_cols].values
    n_samples = min(len(samples_A), len(samples_B))

    for alpha in blend_ratios:
        for i in range(n_samples):
            blend = alpha * samples_A[i] + (1 - alpha) * samples_B[i]
            proba = rf.predict_proba([blend])[0]
            pred_label = rf.classes_[np.argmax(proba)]
            conf = np.max(proba)
            ent = entropy(proba, base=2)
            results.append({
                "Country_A": cA, "Country_B": cB,
                "Blend_A": alpha, "Blend_B": 1 - alpha,
                "Predicted": pred_label,
                "Confidence": conf,
                "Entropy": ent
            })

blend_df = pd.DataFrame(results)
blend_df.to_csv("synthetic_blend_country_entropy.csv", index=False)
print("✔ Saved: synthetic_blend_country_entropy.csv")

# -------------------------
# 4) Identify switch points (tipping thresholds)
# -------------------------
switch_points = []
for (cA, cB), subset in blend_df.groupby(["Country_A", "Country_B"]):
    subset = subset.sort_values("Blend_A")
    preds = subset["Predicted"].values
    blends = subset["Blend_A"].values
    for i in range(1, len(preds)):
        if preds[i] != preds[i - 1]:
            switch_points.append({
                "Country_A": cA, "Country_B": cB,
                "Switch_From": preds[i - 1], "Switch_To": preds[i],
                "Blend_Percent_A": blends[i],
                "Blend_Percent_B": 1 - blends[i]
            })
            break

switch_df = pd.DataFrame(switch_points)
switch_df.to_csv("synthetic_country_switch_points.csv", index=False)
print("✔ Saved: synthetic_country_switch_points.csv")

# ===========================================================
# Pairwise Entropy Trajectories (Cross-Country)
# ===========================================================
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math

sns.set_theme(style="white", context="paper")

# --------------------------------
# Define country list and parameters
# --------------------------------
countries = sorted(set(blend_df["Country_A"]) | set(blend_df["Country_B"]))
n_pairs = len(blend_df.groupby(["Country_A", "Country_B"]))
max_entropy = np.log2(len(rf.classes_))

# Grid dimensions
ncols = 7
nrows = math.ceil(n_pairs / ncols)
palette = sns.color_palette("Spectral", n_colors=len(countries))
color_map = dict(zip(countries, palette))

# --------------------------------
# Create subplots
# --------------------------------
fig, axes = plt.subplots(nrows, ncols, figsize=(16, 8), sharey=True)
axes = axes.flatten()

# --------------------------------
# Loop over all donor–recipient pairs
# --------------------------------
for i, ((cA, cB), subset) in enumerate(blend_df.groupby(["Country_A", "Country_B"])):
    ax = axes[i]

    # Compute mean ± SD entropy across replicates
    summary = subset.groupby("Blend_A")["Entropy"].agg(["mean", "std"]).reset_index()

    # Plot mean and confidence band
    ax.plot(
        summary["Blend_A"], summary["mean"],
        lw=2, color=color_map.get(cA, "black"), label=f"{cA}"
    )
    ax.fill_between(
        summary["Blend_A"],
        summary["mean"] - summary["std"],
        summary["mean"] + summary["std"],
        color=color_map.get(cA, "black"), alpha=0.25
    )

    # Add max entropy reference line
    ax.axhline(max_entropy, linestyle="--", color="lightgray", lw=1.2)

    # Format each subplot
    ax.set_title(f"{cA} ↔ {cB}", fontsize=9, weight="bold")
    ax.set_xlabel("Contamination fraction (α)", fontsize=8)
    if i % ncols == 0:
        ax.set_ylabel("Entropy (Uncertainty)", fontsize=8)
    ax.set_ylim(0, max_entropy + 0.3)
    sns.despine(ax=ax)

# --------------------------------
# Hide empty panels if any
# --------------------------------
for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

# --------------------------------
# Global figure settings
# --------------------------------
fig.suptitle("Cross-Country Pairwise Entropy Trajectories During Synthetic Blending", fontsize=12, weight="bold", y=1.02)
plt.tight_layout()

# Optional save
# plt.savefig("Supplementary_Figure_S1_Pairwise_Entropy.tiff", dpi=600, bbox_inches="tight")

plt.show()
print(f"✔ Generated {i+1} pairwise entropy trajectory plots across {len(countries)} countries.")

# ===========================================================
# Country-Level Entropy Trajectories (Enhanced Formatting)
# ===========================================================
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math

# Setup
sns.set_theme(style="white", context="paper")
max_entropy = np.log2(len(rf.classes_))

# Include all countries appearing in donor or recipient
countries = sorted(set(blend_df["Country_A"]) | set(blend_df["Country_B"]))
n_panels = len(countries)
ncols = 3
nrows = math.ceil(n_panels / ncols)

# Color map
palette = sns.color_palette("Spectral", n_colors=len(countries))
color_map = dict(zip(countries, palette))

# Create grid
fig, axes = plt.subplots(nrows, ncols, figsize=(10, 8), sharey=True)
axes = axes.flatten()

for i, countryA in enumerate(countries):
    ax = axes[i]

    # Filter rows where the country appears as donor
    subdf = blend_df[blend_df["Country_A"] == countryA]
    if subdf.empty:
        ax.set_visible(False)
        continue

    # Aggregate mean ± SD
    summary = subdf.groupby("Blend_A")["Entropy"].agg(["mean", "std"]).reset_index()

    # Plot mean ± SD
    ax.plot(summary["Blend_A"], summary["mean"], lw=2.5,
            color=color_map[countryA], label=countryA)
    ax.fill_between(summary["Blend_A"],
                    summary["mean"] - summary["std"],
                    summary["mean"] + summary["std"],
                    color=color_map[countryA], alpha=0.25)

    # Reference line
    ax.axhline(max_entropy, linestyle="--", color="gray", lw=1.2)

    # Styling
    ax.set_title(f"{countryA}", fontsize=13, weight="bold")
    ax.set_xlabel("Contamination fraction (α)", fontsize=11, weight="bold")
    if i % ncols == 0:
        ax.set_ylabel("Entropy (Uncertainty)", fontsize=11, weight="bold")
    ax.tick_params(axis="both", which="major", labelsize=10, width=1.5)
    for spine in ax.spines.values():
        spine.set_linewidth(1.8)

    ax.set_ylim(0, max_entropy + 0.2)
    sns.despine(ax=ax)

# Hide any remaining empty axes
for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

# Global styling
fig.suptitle("",
             fontsize=14, weight="bold", y=1.02)

plt.tight_layout()
plt.savefig("Entropy_Trajectories.tiff", dpi=600, bbox_inches="tight")
plt.show()

print(f"✔ Generated entropy trajectories for {n_panels} countries.")

# ===========================================================
# Country-Level Switch Point (MDC) Heatmap — Publication Style
# ===========================================================

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Build the switch-point (MDC) matrix
countries = sorted(set(switch_df["Country_A"]) | set(switch_df["Country_B"]))
matrix = pd.DataFrame(index=countries, columns=countries, dtype=float)

for _, row in switch_df.iterrows():
    a, b = row["Country_A"], row["Country_B"]
    matrix.loc[a, b] = row["Blend_Percent_A"]
    matrix.loc[b, a] = row["Blend_Percent_B"]

# --- Optional: fill diagonal with NaN for visual clarity
np.fill_diagonal(matrix.values, np.nan)

# --- Define colormap limits centered for 0–1
vmin, vmax = 0, 1

# --- Plot
plt.figure(figsize=(7.2, 5.5))
sns.set_theme(style="white", context="paper")

ax = sns.heatmap(
    matrix.astype(float), annot=True, fmt=".2f", cmap="coolwarm_r",
    linewidths=0.8, linecolor="white",
    cbar_kws={"label": "Blend ratio (α at switch)"},
    vmin=vmin, vmax=vmax, annot_kws={"fontsize": 9, "weight": "bold"}
)

# --- Aesthetics
ax.set_xlabel("To Country", fontsize=11, weight="bold")
ax.set_ylabel("From Country", fontsize=11, weight="bold")
ax.set_title("Country-Level Switch Points (MDC)", fontsize=12, weight="bold", pad=10)

# Rotate tick labels for readability
plt.xticks(rotation=45, ha="right", fontsize=9)
plt.yticks(rotation=0, fontsize=9)

# Add borders
for _, spine in ax.spines.items():
    spine.set_visible(True)
    spine.set_linewidth(1.2)
    spine.set_color("black")

sns.despine(left=False, bottom=False)
plt.tight_layout()
plt.savefig("SwitchPoint_Heatmap.tiff", dpi=600, bbox_inches="tight")
plt.show()

# ===========================================================
# Country-Level Ecological Dominance Matrix (Publication Style)
# ===========================================================

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Build dominance matrix
countries_in_switch = sorted(list(set(switch_df["Country_A"]) | set(switch_df["Country_B"])))
dominance_country = pd.DataFrame(0, index=countries_in_switch, columns=countries_in_switch)

for _, row in switch_df.iterrows():
    # Define winner and loser based on the blend proportion (A loses when it flips before 0.5)
    winner = row["Country_B"] if row["Blend_Percent_A"] > 0.5 else row["Country_A"]
    loser = row["Country_A"] if row["Blend_Percent_A"] > 0.5 else row["Country_B"]
    if winner in dominance_country.index and loser in dominance_country.columns:
        dominance_country.loc[winner, loser] += 1

# --- Normalize dominance frequencies (optional aesthetic for gradient scaling)
dom_norm = dominance_country.div(dominance_country.sum(axis=1).replace(0, np.nan), axis=0)

# --- Plot
plt.figure(figsize=(7, 5.5))
sns.set_theme(style="white", context="paper")

ax = sns.heatmap(
    dominance_country, annot=True, fmt="d", cmap="crest",
    linewidths=0.8, linecolor="white",
    cbar_kws={"label": "Dominance frequency (wins)"},
    annot_kws={"fontsize": 9, "weight": "bold"}
)

# --- Aesthetics
ax.set_xlabel("Loser", fontsize=11, weight="bold")
ax.set_ylabel("Winner", fontsize=11, weight="bold")
ax.set_title("Country-Level Ecological Dominance Matrix", fontsize=12, weight="bold", pad=10)

# Rotate tick labels for readability
plt.xticks(rotation=45, ha="right", fontsize=10)
plt.yticks(rotation=0, fontsize=10)

# Remove spines for a cleaner look
for _, spine in ax.spines.items():
    spine.set_visible(True)
    spine.set_linewidth(1.3)
    spine.set_color("black")

sns.despine(left=False, bottom=False)
plt.tight_layout()
plt.savefig("Country_Dominance_Matrix.tiff", dpi=600, bbox_inches="tight")
plt.show()

# ===========================================================
# Country-Level Composite Ecological Risk — Publication Style
# ===========================================================

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

sns.set_theme(style="white", context="paper")

# Ensure risk_df is not empty and contains Risk_Primary before plotting
if not risk_df.empty and "Risk_Primary" in risk_df.columns:
    # Sort by descending risk
    risk_order = risk_df["Risk_Primary"].sort_values(ascending=True)
    risk_df = risk_df.loc[risk_order.index]

    # Define color palette: gradient reflecting risk intensity
    colors = sns.color_palette("coolwarm", n_colors=len(risk_df))

    plt.figure(figsize=(7, 3))
    ax = sns.barplot(
        data=risk_df.reset_index(),
        y="index", x="Risk_Primary",
        palette=colors, edgecolor="black", lw=0.8
    )

    # Aesthetics
    ax.set_xlabel("Composite ecological risk", fontsize=12, weight="bold")
    ax.set_ylabel("Country", fontsize=10, weight="bold")
    ax.set_title("", fontsize=12, weight="bold", pad=10)

    # Highlight highest and lowest for contrast
    # max_country = risk_df["Risk_Primary"].idxmax()
    # min_country = risk_df["Risk_Primary"].idxmin() # This is South Africa

    # Add labels to bars, excluding South Africa
    # for container in ax.containers:
    #     for bar in container:
    #         country = bar.get_y() + bar.get_height() / 2.
    #         # Get the country name from the y-axis tick labels
    #         country_name = ax.get_yticklabels()[int(country)].get_text()
    #         if country_name != "South Africa":
    #             ax.annotate(f'{bar.get_width():.2f}',
    #                         xy=(bar.get_width(), bar.get_y() + bar.get_height() / 2),
    #                         xytext=(5, 0), # 5 points horizontal offset
    #                         textcoords="offset points",
    #                         ha='left', va='center',
    #                         fontsize=8,
    #                        )


    sns.despine(left=True, bottom=True)

    # Colorbar legend to interpret risk intensity
    sm = plt.cm.ScalarMappable(cmap="coolwarm", norm=plt.Normalize(risk_df["Risk_Primary"].min(), risk_df["Risk_Primary"].max()))
    sm.set_array([])
    cbar = plt.colorbar(sm, ax=ax, orientation="horizontal", pad=0.2, aspect=30)
    cbar.set_label("Relative ecological vulnerability", fontsize=10, weight="bold")

    plt.tight_layout()
    plt.savefig("Country_Ecological_Risk_Barplot.tiff", dpi=600, bbox_inches="tight")
    plt.show()
else:
    print("Risk data is not available or empty for plotting the bar chart.")

# ===============================
# Country-Level Donor–Recipient Synthetic Blending Simulation
# ===============================
# Author: Suleiman Aminu
# Based on GRUMB v2 donor–recipient simulation framework
# ===============================

import numpy as np, pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from math import sqrt
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------
# 0. Load data
# -------------------------
tpm = pd.read_csv("TPM_clr_batch_corrected_v1.csv", index_col=0)
meta = pd.read_csv("Merged_metadata.csv")

common = tpm.columns.intersection(meta["Sample_ID"])
tpm = tpm[common]
meta = meta[meta["Sample_ID"].isin(common)].reset_index(drop=True)
tpm = tpm[meta["Sample_ID"]]

X = tpm.T.values
y = meta["Country"].values
countries = meta["Country"].unique()
print(f"✔ Data loaded: {X.shape}, countries = {len(countries)}")

# -------------------------
# 1. Train model
# -------------------------
rf = RandomForestClassifier(
    n_estimators=500, max_depth=None, max_features=0.5,
    class_weight="balanced", random_state=42, n_jobs=-1
)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
rf.fit(X_tr, y_tr)
print(f"✔ RandomForest trained — hold-out accuracy: {rf.score(X_te, y_te):.3f}")

# -------------------------
# 2. Define helpers
# -------------------------
def wilson_ci(k, n, z=1.96):
    if n == 0: return (0.0, 0.0)
    p = k / n
    denom = 1 + z**2/n
    center = (p + z**2/(2*n)) / denom
    half = z * sqrt(p*(1-p)/n + z**2/(4*n**2)) / denom
    return max(0, center - half), min(1, center + half)

def mix_samples(x_rec, x_don, alpha):
    return (1-alpha) * x_rec + alpha * x_don

# -------------------------
# 3. Run synthetic blending simulations
# -------------------------
alphas = np.linspace(0, 1, 21)
n_pairs = 30
records = []

grouped = {c: X[meta["Country"] == c] for c in countries}
rng = np.random.default_rng(42)

for rec in countries:
    for don in countries:
        if rec == don: continue
        X_rec, X_don = grouped[rec], grouped[don]
        for a in alphas:
            cnt = 0
            for _ in range(n_pairs):
                x_r = X_rec[rng.integers(0, len(X_rec))]
                x_d = X_don[rng.integers(0, len(X_don))]
                x_mix = mix_samples(x_r, x_d, a).reshape(1, -1)
                cnt += (rf.predict(x_mix)[0] == don)
            p = cnt / n_pairs
            lo, hi = wilson_ci(cnt, n_pairs)
            records.append({"Recipient": rec, "Donor": don, "alpha": a, "P_donor": p, "CI_low": lo, "CI_high": hi})

sim_df = pd.DataFrame(records)
sim_df.to_csv("Country_DonorRecipient_Simulations.csv", index=False)
print("✔ Simulation completed and saved.")

# -------------------------
# 4. Minimal Detectable Contamination (MDC)
# -------------------------
def min_detectable_alpha(sub, thresh=0.8):
    sub = sub.sort_values("alpha")
    hit = sub[sub["P_donor"] >= thresh]
    return hit["alpha"].iloc[0] if len(hit) else np.nan

mdc_rows = []
for rec in countries:
    for don in countries:
        if rec == don: continue
        sub = sim_df[(sim_df["Recipient"]==rec)&(sim_df["Donor"]==don)]
        mdc_rows.append({"Recipient":rec,"Donor":don,"MDC":min_detectable_alpha(sub)})
mdc_df = pd.DataFrame(mdc_rows)
mdc_df.to_csv("Country_MDC_Table.csv", index=False)
print("✔ MDC table saved.")

# ===========================================================
# CLEAN MULTI-PANEL DOSE–RESPONSE WITH COMPLETE LEGEND
# ===========================================================

import matplotlib.pyplot as plt
import seaborn as sns
import math
import pandas as pd

# Load simulation results
sim_df = pd.read_csv("Country_DonorRecipient_Simulations.csv")
countries = sorted(sim_df["Recipient"].unique())

# Grid layout
ncols = 4
nrows = math.ceil(len(countries) / ncols)

# Color palette
palette = sns.color_palette("Spectral", n_colors=len(countries))
color_map = dict(zip(countries, palette))

# Style setup
sns.set_style("white")
sns.set_context("talk")

fig, axes = plt.subplots(nrows, ncols, figsize=(16, 9), sharey=True)
axes = axes.flatten()

# --- NEW: Build legend handles for *all* donor countries ---
import matplotlib.lines as mlines
legend_handles = [
    mlines.Line2D([], [], color=color_map[c], lw=2, label=c)
    for c in countries
]

for i, rec in enumerate(countries):
    ax = axes[i]
    for don in countries:
        if rec == don:
            continue
        sub = sim_df[(sim_df["Recipient"] == rec) & (sim_df["Donor"] == don)]
        if len(sub) == 0:
            continue

        ax.plot(
            sub["alpha"], sub["P_donor"],
            lw=2, color=color_map.get(don, "black"), label=don
        )

        ax.fill_between(
            sub["alpha"], sub["CI_low"], sub["CI_high"],
            color=color_map.get(don, "black"), alpha=0.15
        )

    ax.axhline(0.8, color="gray", linestyle="--", lw=1)
    ax.set_ylim(0, 1.05)
    ax.set_xlabel("Contamination fraction (α)", fontsize=10)
    if i % ncols == 0:
        ax.set_ylabel("P(predicted donor)", fontsize=10)
    ax.set_title(f"Recipient: {rec}", fontsize=11, weight="bold")
    sns.despine(ax=ax)
    ax.grid(False)
    for spine in ax.spines.values():
        spine.set_linewidth(1.2)

# Hide extra subplots if fewer than grid cells
for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

# Unified legend — now includes ALL donor countries (Benin included)
fig.legend(
    handles=legend_handles,
    loc="upper center", bbox_to_anchor=(0.5, -0.02),
    ncol=8, frameon=False, fontsize=9,
    title="Donor Country", title_fontsize=10
)

# Title and layout
plt.tight_layout(rect=[0, 0.05, 1, 0.96])
fig.suptitle("Cross-Country Synthetic Contamination Trajectories",
             fontsize=15, weight="bold", y=0.995)

plt.show()

print("✔ Figure updated — Benin now included in the legend.")



# -------------------------
#  Plot MDC Heatmap
# -------------------------
hm = mdc_df.pivot(index="Recipient", columns="Donor", values="MDC")
plt.figure(figsize=(7,6))
sns.heatmap(hm, annot=True, fmt=".2f", cmap="coolwarm_r", cbar_kws={"label":"MDC (α ≥ 80%)"})
plt.title("Country-Level MDC Heatmap", weight="bold")
plt.xlabel("Donor Country")
plt.ylabel("Recipient Country")
sns.despine()
plt.tight_layout()
plt.savefig("Country_MDC_Heatmap.tiff", dpi=600)
plt.show()

print("✔ Plots saved (dose–response + heatmap).")

# ===========================================================
# Cross-Country Dose–Response Visualization (Enhanced)
# ===========================================================
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math

# Load results (already computed)
sim_df = pd.read_csv("Country_DonorRecipient_Simulations.csv")

# Ensure consistent color palette
countries = sorted(sim_df["Recipient"].unique())
palette = sns.color_palette("Spectral", n_colors=len(countries))
color_map = dict(zip(countries, palette))

# Layout setup
sns.set_theme(style="white", context="paper")
ncols = 4
nrows = math.ceil(len(countries) / ncols)
fig, axes = plt.subplots(nrows, ncols, figsize=(16, 9), sharey=True)
axes = axes.flatten()

# Plot each recipient’s dose–response trajectories
for i, rec in enumerate(countries):
    ax = axes[i]
    for don in countries:
        if rec == don:
            continue
        sub = sim_df[(sim_df["Recipient"] == rec) & (sim_df["Donor"] == don)]
        if len(sub) == 0:
            continue

        # Main line and CI ribbon
        ax.plot(sub["alpha"], sub["P_donor"], lw=2.5,
                color=color_map.get(don, "black"), label=don)
        ax.fill_between(sub["alpha"], sub["CI_low"], sub["CI_high"],
                        color=color_map.get(don, "black"), alpha=0.2)

    # Add reference line for 80% threshold
    ax.axhline(0.8, color="gray", linestyle=":", lw=1.5)

    # Axis labels and titles
    ax.set_title(f"Recipient: {rec}", fontsize=13, weight="bold")
    ax.set_xlabel("Contamination fraction (α)", fontsize=11, weight="bold")
    if i % ncols == 0:
        ax.set_ylabel("P(predicted donor)", fontsize=11, weight="bold")

    # Aesthetic adjustments
    ax.set_ylim(0, 1.02)
    ax.tick_params(axis="both", which="major", labelsize=10, width=1.5)
    for spine in ax.spines.values():
        spine.set_linewidth(1.8)
    sns.despine(ax=ax)

# Hide any unused panels
for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

# Centralized legend (outside the grid)
handles, labels = ax.get_legend_handles_labels()
fig.legend(handles, labels, loc='lower center', bbox_to_anchor=(0.5, -0.03),
           ncol=7, fontsize=10, frameon=False, title="Donor Country", title_fontsize=11, handlelength=1.5)

# Global title and layout
fig.suptitle("Cross-Country Synthetic Contamination Trajectories",
             fontsize=15, weight="bold", y=1.02)
plt.tight_layout(rect=[0, 0.03, 1, 0.98])

# Optional save
plt.savefig("DoseResponse_actual.tiff", dpi=600, bbox_inches="tight")

plt.show()
print(f"✔ Enhanced dose–response multi-panel figure generated for {len(countries)} countries.")